### ISSUE TITLE
main/harfbuzz-icu-5.1.0 building fails due to 'PKG/usr/lib/libharfbuzz-icu*': No such file or directory

### ISSUE THREAD

**Issue by Ouaille-Aime-Scier** [venomlinux/ports#1297]
`Found ninja-1.11.0 at /usr/bin/ninja
+ meson compile -C build
ninja: Entering directory `/var/cache/scratchpkg/work/harfbuzz-icu/src/build'
[277/277] Linking target util/hb-subset
+ DESTDIR=/var/cache/scratchpkg/work/harfbuzz-icu/src/PKG meson install -C build
ninja: Entering directory `/var/cache/scratchpkg/work/harfbuzz-icu/src/build'
ninja: no work to do.
Installing src/libharfbuzz.so.0.50100.0 to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64
Installing src/libharfbuzz-subset.so.0.50100.0 to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64
Installing src/libharfbuzz-icu.so.0.50100.0 to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64
Installing src/hb-gobject-enums.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz
Installing src/libharfbuzz-gobject.so.0.50100.0 to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64
Installing src/HarfBuzz-0.0.gir to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/share/gir-1.0
Installing src/HarfBuzz-0.0.typelib to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64/girepository-1.0
Installing util/hb-view to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/bin
Installing util/hb-shape to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/bin
Installing util/hb-subset to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/bin
Installing util/hb-ot-shape-closure to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/bin
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-icu.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-gobject.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-gobject-structs.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-aat-layout.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-aat.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-blob.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-buffer.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-common.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-cplusplus.hh to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-deprecated.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-draw.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-face.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-font.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-map.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-ot-color.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-ot-deprecated.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-ot-font.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-ot-layout.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-ot-math.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-ot-meta.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-ot-metrics.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-ot-name.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-ot-shape.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-ot-var.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-ot.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-set.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-shape-plan.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-shape.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-style.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-unicode.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/build/src/hb-version.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-ft.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-glib.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-subset.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-subset-repacker.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/build/src/hb-version.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/build/meson-private/harfbuzz.pc to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64/pkgconfig
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/build/meson-private/harfbuzz-subset.pc to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64/pkgconfig
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/build/meson-private/harfbuzz-icu.pc to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64/pkgconfig
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/build/src/harfbuzz-config.cmake to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64/cmake/harfbuzz
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/build/meson-private/harfbuzz-gobject.pc to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64/pkgconfig
Installing symlink pointing to libharfbuzz.so.0.50100.0 to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64/libharfbuzz.so.0
Installing symlink pointing to libharfbuzz.so.0 to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64/libharfbuzz.so
Installing symlink pointing to libharfbuzz-subset.so.0.50100.0 to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64/libharfbuzz-subset.so.0
Installing symlink pointing to libharfbuzz-subset.so.0 to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64/libharfbuzz-subset.so
Installing symlink pointing to libharfbuzz-icu.so.0.50100.0 to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64/libharfbuzz-icu.so.0
Installing symlink pointing to libharfbuzz-icu.so.0 to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64/libharfbuzz-icu.so
Installing symlink pointing to libharfbuzz-gobject.so.0.50100.0 to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64/libharfbuzz-gobject.so.0
Installing symlink pointing to libharfbuzz-gobject.so.0 to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64/libharfbuzz-gobject.so
+ mkdir -p /var/cache/scratchpkg/work/harfbuzz-icu/pkg/usr/lib/pkgconfig /var/cache/scratchpkg/work/harfbuzz-icu/pkg/usr/include/harfbuzz
+ mv PKG/usr/include/harfbuzz/hb-icu.h /var/cache/scratchpkg/work/harfbuzz-icu/pkg/usr/include/harfbuzz/
+ mv PKG/usr/lib/libharfbuzz-icu* /var/cache/scratchpkg/work/harfbuzz-icu/pkg/usr/lib/
mv: cannot stat 'PKG/usr/lib/libharfbuzz-icu*': No such file or directory
==> ERROR: Build failed: harfbuzz-icu-5.1.0-1`

**Comment by AldairbotHerotaku** [comment]
i think is because it shuld be $PKG/usr but it calls to PKG
