### ISSUE TITLE
3.0/main/firefox-103.0.1 building fails with harfbuzz not found in pkg-config search path

### ISSUE THREAD

**Issue by Ouaille-Aime-Scier** [venomlinux/ports#1310]
` 0:05.52 checking for nodejs... /usr/bin/node (18.7.0)
 0:05.53 checking for gtk+-wayland-3.0 >= 3.14 xkbcommon >= 0.4.1 libdrm >= 2.4... no
 0:05.53 WARNING: Package gtk+-wayland-3.0 was not found in the pkg-config search path.
 0:05.53 WARNING: Perhaps you should add the directory containing `gtk+-wayland-3.0.pc'
 0:05.53 WARNING: to the PKG_CONFIG_PATH environment variable
 0:05.53 WARNING: Package 'gtk+-wayland-3.0', required by 'virtual:world', not found
 0:05.55 checking for pango >= 1.22.0... no
 0:05.55 ERROR: Package harfbuzz was not found in the pkg-config search path.
 0:05.55 ERROR: Perhaps you should add the directory containing `harfbuzz.pc'
 0:05.55 ERROR: to the PKG_CONFIG_PATH environment variable
 0:05.55 ERROR: Package 'harfbuzz', required by 'pango', not found
*** Fix above errors and then restart with "./mach build"
==> ERROR: Build failed: firefox-103.0.1-1`

**Comment by Visone-Selektah** [comment]
Check if `revdep` shows some errors about harfbuzz

**Comment by Ouaille-Aime-Scier** [comment]
> Check if `revdep` shows some errors about harfbuzz

Yes I have done a revdep and I have rebuild harfbuzz but no matter firefox upgrading still fails. Perhaps an issue due to this commit : 
`https://github.com/venomlinux/ports/pull/1309/commits/0a4ab99d18e85b3ffe921e4653bc9f9791bf27d9`

**Comment by Visone-Selektah** [comment]
There's this fix pending to merge
https://github.com/venomlinux/ports/pull/1303/commits/e361477dbbd5477d05ccc30e0b3e686d1a173318

**Comment by lumarogit** [comment]
> > Check if `revdep` shows some errors about harfbuzz
> 
> Yes I have done a revdep and I have rebuild harfbuzz but no matter firefox upgrading still fails. Perhaps an issue due to this commit : `https://github.com/venomlinux/ports/pull/1309/commits/0a4ab99d18e85b3ffe921e4653bc9f9791bf27d9`

Hi, check the installation files with 'scratch files harfbuzz' and see if the libraries are installed in /usr/lib64, i recently had a problem with this. 

Try uninstalling harfbuzz and removing the package from the cache in '/var/cache/scratchpkg/packages' and reinstalling it. Another way to see what lib64 points to is with 'scratch provide /usr/lib64/$' (can check '/usr/lib/$' too). The problem is with harfbuzz, not harfbuzz-icu, based on the data you show.

**Comment by Ouaille-Aime-Scier** [comment]
> Hi, check the installation files with 'scratch files harfbuzz' and see if the libraries are installed in /usr/lib64, i recently had a problem with this.
> Try uninstalling harfbuzz and removing the package from the cache in '/var/cache/scratchpkg/packages' and reinstalling it. Another way to see what lib64 points to is with 'scratch provide /usr/lib64/$' (can check '/usr/lib/$' too). The problem is with harfbuzz, not harfbuzz-icu, based on the data you show.
`sudo scratch files harfbuzz
5.1.0 1
usr/
usr/lib64/
usr/lib64/libharfbuzz.so.0.50100.0
usr/lib64/libharfbuzz-subset.so.0.50100.0
usr/lib64/libharfbuzz-gobject.so.0.50100.0
usr/lib64/girepository-1.0/
usr/lib64/girepository-1.0/HarfBuzz-0.0.typelib
usr/lib64/pkgconfig/
usr/lib64/pkgconfig/harfbuzz.pc
usr/lib64/pkgconfig/harfbuzz-subset.pc
usr/lib64/pkgconfig/harfbuzz-gobject.pc
usr/lib64/cmake/
usr/lib64/cmake/harfbuzz/
usr/lib64/cmake/harfbuzz/harfbuzz-config.cmake
usr/lib64/libharfbuzz.so.0
usr/lib64/libharfbuzz.so
usr/lib64/libharfbuzz-subset.so.0
usr/lib64/libharfbuzz-subset.so
usr/lib64/libharfbuzz-gobject.so.0
usr/lib64/libharfbuzz-gobject.so
usr/include/
usr/include/harfbuzz/
usr/include/harfbuzz/hb-gobject-enums.h
usr/include/harfbuzz/hb-gobject.h
usr/include/harfbuzz/hb-gobject-structs.h
usr/include/harfbuzz/hb-aat-layout.h
usr/include/harfbuzz/hb-aat.h
usr/include/harfbuzz/hb-blob.h
usr/include/harfbuzz/hb-buffer.h
usr/include/harfbuzz/hb-common.h
usr/include/harfbuzz/hb-cplusplus.hh
usr/include/harfbuzz/hb-deprecated.h
usr/include/harfbuzz/hb-draw.h
usr/include/harfbuzz/hb-face.h
usr/include/harfbuzz/hb-font.h
usr/include/harfbuzz/hb-map.h
usr/include/harfbuzz/hb-ot-color.h
usr/include/harfbuzz/hb-ot-deprecated.h
usr/include/harfbuzz/hb-ot-font.h
usr/include/harfbuzz/hb-ot-layout.h
usr/include/harfbuzz/hb-ot-math.h
usr/include/harfbuzz/hb-ot-meta.h
usr/include/harfbuzz/hb-ot-metrics.h
usr/include/harfbuzz/hb-ot-name.h
usr/include/harfbuzz/hb-ot-shape.h
usr/include/harfbuzz/hb-ot-var.h
usr/include/harfbuzz/hb-ot.h
usr/include/harfbuzz/hb-set.h
usr/include/harfbuzz/hb-shape-plan.h
usr/include/harfbuzz/hb-shape.h
usr/include/harfbuzz/hb-style.h
usr/include/harfbuzz/hb-unicode.h
usr/include/harfbuzz/hb.h
usr/include/harfbuzz/hb-ft.h
usr/include/harfbuzz/hb-glib.h
usr/include/harfbuzz/hb-subset.h
usr/include/harfbuzz/hb-subset-repacker.h
usr/include/harfbuzz/hb-version.h
usr/share/
usr/share/gir-1.0/
usr/share/gir-1.0/HarfBuzz-0.0.gir
usr/bin/
usr/bin/hb-view
usr/bin/hb-shape
usr/bin/hb-subset
usr/bin/hb-ot-shape-closure`

**Comment by lumarogit** [comment]
# scratch remove harfbuzz
# rm /var/cache/scratchpkg/packages/harfbuzz*
# scratch install harfbuzz
# revdep -r

**Comment by Ouaille-Aime-Scier** [comment]
> # scratch remove harfbuzz
> # rm /var/cache/scratchpkg/packages/harfbuzz*
> # scratch install harfbuzz
> # revdep -r
All done (info : no broken package for revdep) but same error when upgrading Firefox

**Comment by AldairbotHerotaku** [comment]
maybe installing harfbuzz-icu?
idk this error don't heppened to my while i was upgrading it

**Comment by lumarogit** [comment]
It is not necessary to build firefox, I don't have it installed, only harfbuzz.

**Comment by emmett1** [comment]
Try rebuild harfbuzz, harfbuzz-icu and gtk3 (for wayland support).
`scratch install -fr harfbuzz`
`scratch install -fr harfbuzz-icu`
`scratch install wayland`
`scratch install -fr harfbuzz`

**Comment by Ouaille-Aime-Scier** [comment]
> Try rebuild harfbuzz, harfbuzz-icu and gtk3 (for wayland support). `scratch install -fr harfbuzz` `scratch install -fr harfbuzz-icu` `scratch install wayland` `scratch install -fr gtk3`

1/ the reinstall of harfbuzz went fine as usual

2/ the reinstall of harfbuzz-icu get : 
`
ninja: Entering directory `/var/cache/scratchpkg/work/harfbuzz-icu/src/build'
ninja: no work to do.
Installing src/libharfbuzz.so.0.50100.0 to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64
Installing src/libharfbuzz-subset.so.0.50100.0 to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64
Installing src/libharfbuzz-icu.so.0.50100.0 to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64
Installing src/hb-gobject-enums.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz
Installing src/libharfbuzz-gobject.so.0.50100.0 to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64
Installing src/HarfBuzz-0.0.gir to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/share/gir-1.0
Installing src/HarfBuzz-0.0.typelib to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64/girepository-1.0
Installing util/hb-view to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/bin
Installing util/hb-shape to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/bin
Installing util/hb-subset to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/bin
Installing util/hb-ot-shape-closure to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/bin
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-icu.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-gobject.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-gobject-structs.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-aat-layout.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-aat.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-blob.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-buffer.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-common.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-cplusplus.hh to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-deprecated.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-draw.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-face.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-font.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-map.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-ot-color.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-ot-deprecated.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-ot-font.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-ot-layout.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-ot-math.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-ot-meta.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-ot-metrics.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-ot-name.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-ot-shape.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-ot-var.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-ot.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-set.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-shape-plan.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-shape.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-style.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-unicode.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/build/src/hb-version.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-ft.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-glib.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-subset.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/harfbuzz-5.1.0/src/hb-subset-repacker.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz/
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/build/src/hb-version.h to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/include/harfbuzz
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/build/meson-private/harfbuzz.pc to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64/pkgconfig
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/build/meson-private/harfbuzz-subset.pc to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64/pkgconfig
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/build/meson-private/harfbuzz-icu.pc to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64/pkgconfig
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/build/src/harfbuzz-config.cmake to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64/cmake/harfbuzz
Installing /var/cache/scratchpkg/work/harfbuzz-icu/src/build/meson-private/harfbuzz-gobject.pc to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64/pkgconfig
Installing symlink pointing to libharfbuzz.so.0.50100.0 to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64/libharfbuzz.so.0
Installing symlink pointing to libharfbuzz.so.0 to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64/libharfbuzz.so
Installing symlink pointing to libharfbuzz-subset.so.0.50100.0 to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64/libharfbuzz-subset.so.0
Installing symlink pointing to libharfbuzz-subset.so.0 to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64/libharfbuzz-subset.so
Installing symlink pointing to libharfbuzz-icu.so.0.50100.0 to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64/libharfbuzz-icu.so.0
Installing symlink pointing to libharfbuzz-icu.so.0 to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64/libharfbuzz-icu.so
Installing symlink pointing to libharfbuzz-gobject.so.0.50100.0 to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64/libharfbuzz-gobject.so.0
Installing symlink pointing to libharfbuzz-gobject.so.0 to /var/cache/scratchpkg/work/harfbuzz-icu/src/PKG/usr/lib64/libharfbuzz-gobject.so
+ mkdir -p /var/cache/scratchpkg/work/harfbuzz-icu/pkg/usr/lib/pkgconfig /var/cache/scratchpkg/work/harfbuzz-icu/pkg/usr/include/harfbuzz
+ mv PKG/usr/include/harfbuzz/hb-icu.h /var/cache/scratchpkg/work/harfbuzz-icu/pkg/usr/include/harfbuzz/
+ mv PKG/usr/lib/libharfbuzz-icu* /var/cache/scratchpkg/work/harfbuzz-icu/pkg/usr/lib/
mv: cannot stat 'PKG/usr/lib/libharfbuzz-icu*': No such file or directory
==> ERROR: Build failed: harfbuzz-icu-5.1.0-1`

3/ the reinstall of wayland went fine

4/ the reinstall of gtk3 get : 
`==> Build start: gtk3-3.24.34-1
+ build
+ cd gtk+-3.24.34
+ ./configure --prefix=/usr --sysconfdir=/etc
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '0' is supported by ustar format... yes
checking whether GID '0' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether to enable maintainer-specific portions of Makefiles... yes
checking whether make supports nested variables... (cached) yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for gcc... gcc
checking whether the compiler supports GNU C... (cached) yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking how to run the C preprocessor... gcc -E
checking whether gcc and cc understand -c and -o together... yes
checking whether make sets $(MAKE)... (cached) yes
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for wchar.h... yes
checking for minix/config.h... no
checking for sys/param.h... yes
checking whether it is safe to define __EXTENSIONS__... yes
checking whether _XOPEN_SOURCE should be defined... no
checking for a sed that does not truncate output... /bin/sed
checking whether NLS is requested... yes
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for shared library run path origin... done
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking for GNU gettext in libc... yes
checking whether to use NLS... yes
checking where the gettext function comes from... libc
checking for native Win32... no
checking for c++... c++
checking whether the compiler supports GNU C++... yes
checking whether c++ accepts -g... yes
checking for c++ option to enable C++11 features... none needed
checking dependency style of c++... gcc3
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking how to run the C++ preprocessor... c++ -E
checking for ld used by c++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the c++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for c++ option to produce PIC... -fPIC -DPIC
checking if c++ PIC flag -fPIC -DPIC works... yes
checking if c++ static flag -static works... yes
checking if c++ supports -c -o file.o... yes
checking if c++ supports -c -o file.o... (cached) yes
checking whether the c++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
configure: creating ./config.lt
config.lt: creating libtool
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking dependency style of gcc... gcc3
checking for nm... /usr/bin/nm -B
checking for some Win32 platform... no
checking for shm_open in -lrt... yes
checking for posix_fallocate... yes
checking for flockfile... yes
checking for _lock_file... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for wayland-scanner... /usr/bin/wayland-scanner
checking for WAYLAND_DEPENDENCIES... no
checking whether build environment is sane... yes
checking for BASE_DEPENDENCIES... no
configure: error: Package requirements (glib-2.0 >= 2.57.2    atk >= 2.32.0    pango >= 1.41.0    fribidi >= 0.19.7    cairo >= 1.14.0    cairo-gobject >= 1.14.0    gdk-pixbuf-2.0 >= 2.30.0) were not met:

Package 'harfbuzz', required by 'pango', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables BASE_DEPENDENCIES_CFLAGS
and BASE_DEPENDENCIES_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
==> ERROR: Build failed: gtk3-3.24.34-1`

**Comment by emmett1** [comment]
Whats the output of `scratch provide /usr/lib64/$`?

**Comment by Ouaille-Aime-Scier** [comment]
> `scratch provide /usr/lib64/$`?

graphviz	usr/lib64/
harfbuzz	usr/lib64/
wayland	usr/lib64/

**Comment by emmett1** [comment]
Something is wrong with your system, /usr/lib64 should not be used in venom. Try rebuild graphviz, harfbuzz then wayland. (Rebuild = scratch install -fr pkg)
