### ISSUE TITLE
Mesa still fails to compile

### ISSUE THREAD

**Issue by Pelle-B** [venomlinux/ports#1513]
I get`Running custom install script '/usr/bin/python3 /var/cache/scratchpkg/work/mesa/src/mesa-22.1.7/bin/install_megadrivers.py /var/cache/scratchpkg/work/mesa/src/mesa-22.1.7/build/src/gallium/targets/va/libgallium_drv_video.so lib64/dri r600_drv_video.so radeonsi_drv_video.so nouveau_drv_video.so'
+ ln -s libGLX_mesa.so.0 /var/cache/scratchpkg/work/mesa/pkg/usr/lib/libGLX_indirect.so.0
ln: failed to create symbolic link '/var/cache/scratchpkg/work/mesa/pkg/usr/lib/libGLX_indirect.so.0': No such file or directory
`
libGLX_mesa.so.0 exists in /usr/lib

**Comment by Pelle-B** [comment]
Now I get:
`Run-time dependency vdpau found: YES 1.5
Program glslangValidator found: NO

../meson.build:683:2: ERROR: Program 'glslangValidator' not found or not executable

A full log can be found at /var/cache/scratchpkg/work/mesa/src/mesa-22.2.0-rc3/build/meson-logs/meson-log.txt
==> ERROR: Build failed: mesa-22.2.0-rc3`

And revdep says  libLLVM-14.so is missing...

**Comment by Visone-Selektah** [comment]
Hi!
That's a vulkan dep, install glslang
About llvm, did you update to llvm 15? if not, update llvm first, then mesa

**Comment by Pelle-B** [comment]
I did, now I am back to the first issue.

**Comment by Visone-Selektah** [comment]
Hi!
 Try installing glslang

**Comment by Pelle-B** [comment]
I did install glslang, that is what took me back to the issue mentioned first.

**Comment by Visone-Selektah** [comment]
Hi!
I have that errors in some tryouts but it isn't consistent, I'll look into it but meanwhile try to build it using 
     `scratch install -fr mesa`

**Comment by Pelle-B** [comment]
I did (and I think I have done it before), same error persists. I have not made any changes to the system other than upgrading since last time I succesfully upgraded Mesa.

**Comment by lumarogit** [comment]
Hi, sync and reinstall mesa with new updated spkgbuild.

scratch sync && scratch install -fr mesa

**Comment by Pelle-B** [comment]
Succes! Wonderful!
