### ISSUE TITLE
Openbox 

### ISSUE THREAD

**Issue by drmarwat** [venomlinux/ports#156]
Would it not be more convenient to have openbox port with all related packages and one can put a request for missing packages?

**Comment by emmett1** [comment]
openbox already in the repo
https://github.com/emmett1/ports/tree/master/core/openbox

**Comment by drmarwat** [comment]
I meant a separate repository for all openbox related packages

**Comment by emmett1** [comment]
it only has a little openbox related packages, so no need separate repository
