### ISSUE TITLE
gksu

### ISSUE THREAD

**Issue by drmarwat** [venomlinux/ports#158]
Kindly ass gksu to ports please

**Comment by emmett1** [comment]
gksu is deprecated and its even removed from debian and ubuntu repo.
why do you need gksu anyway?

**Comment by drmarwat** [comment]
yes I know gksu is dead but for lot of things I commonly use it e.g
running thunar as sudo with needing password

**Comment by emmett1** [comment]
you can run 'pkexec thunar' for that.
