### ISSUE TITLE
Latest Rust will not compile

### ISSUE THREAD

**Issue by Pelle-B** [venomlinux/ports#1676]
Version 1.63.0-1
The last of the output in xterm:
`CXX_x86_64-unknown-linux-gnu = Some("c++")
  CXXFLAGS_x86_64-unknown-linux-gnu = Some("-ffunction-sections -fdata-sections -fPIC -m64 -march=x86-64 -pipe -fomit-frame-pointer")
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,llvm14-builtins-abi,sse,sse2")
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-march=x86-64" "-pipe" "-fomit-frame-pointer" "-I/usr/include" "-std=c++14" "-fno-exceptions" "-D_GNU_SOURCE" "-D__STDC_CONSTANT_MACROS" "-D__STDC_FORMAT_MACROS" "-D__STDC_LIMIT_MACROS" "-DLLVM_COMPONENT_AMDGPU" "-DLLVM_COMPONENT_ASMPARSER" "-DLLVM_COMPONENT_BITREADER" "-DLLVM_COMPONENT_BITWRITER" "-DLLVM_COMPONENT_BPF" "-DLLVM_COMPONENT_COVERAGE" "-DLLVM_COMPONENT_INSTRUMENTATION" "-DLLVM_COMPONENT_IPO" "-DLLVM_COMPONENT_LINKER" "-DLLVM_COMPONENT_LTO" "-DLLVM_COMPONENT_NVPTX" "-DLLVM_COMPONENT_WEBASSEMBLY" "-DLLVM_COMPONENT_X86" "-DNDEBUG" "-o" "/var/cache/scratchpkg/work/rust/src/rustc-1.63.0-src/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/build/rustc_llvm-5137e0cac6014676/out/llvm-wrapper/PassWrapper.o" "-c" "llvm-wrapper/PassWrapper.cpp"
  cargo:warning=llvm-wrapper/PassWrapper.cpp: In lambda function:
  cargo:warning=llvm-wrapper/PassWrapper.cpp:988:43: error: 'ASanGlobalsMetadataAnalysis' was not declared in this scope
  cargo:warning=  988 |           MPM.addPass(RequireAnalysisPass<ASanGlobalsMetadataAnalysis, Module>());
  cargo:warning=      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=llvm-wrapper/PassWrapper.cpp:988:78: error: template argument 1 is invalid
  cargo:warning=  988 |           MPM.addPass(RequireAnalysisPass<ASanGlobalsMetadataAnalysis, Module>());
  cargo:warning=      |                                                                              ^
  exit status: 1

  --- stderr

  error occurred: Command "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-march=x86-64" "-pipe" "-fomit-frame-pointer" "-I/usr/include" "-std=c++14" "-fno-exceptions" "-D_GNU_SOURCE" "-D__STDC_CONSTANT_MACROS" "-D__STDC_FORMAT_MACROS" "-D__STDC_LIMIT_MACROS" "-DLLVM_COMPONENT_AMDGPU" "-DLLVM_COMPONENT_ASMPARSER" "-DLLVM_COMPONENT_BITREADER" "-DLLVM_COMPONENT_BITWRITER" "-DLLVM_COMPONENT_BPF" "-DLLVM_COMPONENT_COVERAGE" "-DLLVM_COMPONENT_INSTRUMENTATION" "-DLLVM_COMPONENT_IPO" "-DLLVM_COMPONENT_LINKER" "-DLLVM_COMPONENT_LTO" "-DLLVM_COMPONENT_NVPTX" "-DLLVM_COMPONENT_WEBASSEMBLY" "-DLLVM_COMPONENT_X86" "-DNDEBUG" "-o" "/var/cache/scratchpkg/work/rust/src/rustc-1.63.0-src/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/build/rustc_llvm-5137e0cac6014676/out/llvm-wrapper/PassWrapper.o" "-c" "llvm-wrapper/PassWrapper.cpp" with args "c++" did not execute successfully (status code exit status: 1).

warning: build failed, waiting for other jobs to finish...
Build completed unsuccessfully in 0:04:01
==> ERROR: Build failed: rust-1.63.0-1
`

**Comment by Ouaille-Aime-Scier** [comment]
Here is my build.log.
[build.log](https://github.com/venomlinux/ports/files/9541235/build.log)

**Comment by Pelle-B** [comment]
> Here is my build.log.

A quick look makes me think it is the same as mine (if I can find it).

**Comment by heitbaum** [comment]
See
- https://github.com/rust-lang/rust/pull/98621
- https://github.com/rust-lang/rust/pull/98632

**Comment by lumarogit** [comment]
Hi, this version build fine on my system. Try again with the updated version 1.64.0.

**Comment by Pelle-B** [comment]
I close this issue as a new version is out.
