### ISSUE TITLE
LiveCD Installation Script Missing

### ISSUE THREAD

**Issue by DevonIO** [venomlinux/ports#169]
venom-mate-20190627.iso

Downloaded and loaded up on VirtualBox, the command 'venom-installer' is missing, I was unable to find it anyway.

PS- Websites Forums are not working, I registered and it says "Unknown error" whenever I try to post anything.

**Comment by emmett1** [comment]
are sure you run 'venom-installer' as root, or using sudo?

about forum, thanks for the report, its really broken, i will take a look at it.

**Comment by DevonIO** [comment]
Indeed sudo was required, I apologize the LiveCDs I'm used to didn't require it or the LiveCD was logged in as root by default. Can't image why I didnt think of that.
