### ISSUE TITLE
How do you track software releases and determine compatibility between them

### ISSUE THREAD

**Issue by lina-not-linus** [venomlinux/ports#171]
How do you keep track of software releases and determine compatibility between them? Thank you

**Comment by emmett1** [comment]
Theres a script called 'update' on top of directory in the repo. This script will read source version then compare it with source from upstream by using wget + grep + sed + etc gerex to get upstream latest version. The 'update' script will print out outdated (diff version from the one in spkgbuild and upstream) packages version. Those outdated packages I will make sure compiled fine before push here.

**Comment by lina-not-linus** [comment]
Oh, I see. Thank you for your reply. Thank you
