### ISSUE TITLE
Plank will not build 

### ISSUE THREAD

**Issue by FlexCoreOS** [venomlinux/ports#174]
Listed below is the error that is given when trying to install plank.  Note that package "gee" was also being flagged as not being installed as a dependency, but installing the package "libgee" got rid of that error.

bamf-0.5.4

  Build Environment
    Install Prefix:       /usr
    Introspection:        yes
    Headless tests:       no
    Coverage Reporting:   no
    Export actions menus: no

+ make
make  all-recursive
make[1]: Entering directory '/var/cache/scratchpkg/work/bamf/src/bamf-0.5.4'
Making all in lib/libbamf-private
make[2]: Entering directory '/var/cache/scratchpkg/work/bamf/src/bamf-0.5.4/lib/libbamf-private'
  GEN      bamf-gdbus-generated.c
  GEN      bamf-gdbus-view-generated.c
make  all-am
make[3]: Entering directory '/var/cache/scratchpkg/work/bamf/src/bamf-0.5.4/lib/libbamf-private'
  CC       libbamf_private_la-bamf-gdbus-generated.lo
  CC       libbamf_private_la-bamf-gdbus-view-generated.lo
  CCLD     libbamf-private.la
make[3]: Leaving directory '/var/cache/scratchpkg/work/bamf/src/bamf-0.5.4/lib/libbamf-private'
make[2]: Leaving directory '/var/cache/scratchpkg/work/bamf/src/bamf-0.5.4/lib/libbamf-private'
Making all in lib/libbamf
make[2]: Entering directory '/var/cache/scratchpkg/work/bamf/src/bamf-0.5.4/lib/libbamf'
make  all-am
make[3]: Entering directory '/var/cache/scratchpkg/work/bamf/src/bamf-0.5.4/lib/libbamf'
  CC       libbamf3_la-bamf-application.lo
  CC       libbamf3_la-bamf-control.lo
bamf-control.c: In function 'bamf_control_init':
bamf-control.c:100:13: error: G_ADD_PRIVATE [-Werror]
  100 |   priv = self->priv = BAMF_CONTROL_GET_PRIVATE (self);
      |             ^~~~~~~~~~~~~~~
bamf-application.c: In function 'bamf_application_init':
bamf-application.c:746:13: error: G_ADD_PRIVATE [-Werror]
  746 |   priv = self->priv = BAMF_APPLICATION_GET_PRIVATE (self);
      |             ^~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[3]: *** [Makefile:637: libbamf3_la-bamf-control.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
cc1: all warnings being treated as errors
make[3]: *** [Makefile:630: libbamf3_la-bamf-application.lo] Error 1
make[3]: Leaving directory '/var/cache/scratchpkg/work/bamf/src/bamf-0.5.4/lib/libbamf'
make[2]: *** [Makefile:514: all] Error 2
make[2]: Leaving directory '/var/cache/scratchpkg/work/bamf/src/bamf-0.5.4/lib/libbamf'
make[1]: *** [Makefile:460: all-recursive] Error 1
make[1]: Leaving directory '/var/cache/scratchpkg/work/bamf/src/bamf-0.5.4'
make: *** [Makefile:391: all] Error 2
==> ERROR: Build 'bamf-0.5.4-3' failed.

**Comment by emmett1** [comment]
Thanks for the report. Its fixed.
https://github.com/venomlinux/ports/commit/966e94ddf79261e2178da6c9cb4544488199cad8

**Comment by FlexCoreOS** [comment]
Thanks.  Miyolinux told me about this distro.  I like it.

**Comment by emmett1** [comment]
Yeah, Dan is a very good friend.
I'm glad you like it. Just tell me if you need help about this distro :D

**Comment by FlexCoreOS** [comment]
After my big update, I went to install the package, and got this error

==> Source 'bamf-0.5.4.tar.gz' found.
==> ERROR: md5sum=() is empty, please provide it.

**Comment by emmett1** [comment]
Theres a huge changes to scratchpkg from 20191227, md5sum=() deprecated replaced with ‘.checksums’ file can be generate with ‘pkgbuild -g’.
To fix it, run ‘scratch build scratchpkg -m && scratch upgrade scratchpkg’ to build latest scratchpkg with md5sum check skipped then upgrade it. After that scratchpkg should be working normally. Dont forget to run ‘updateconf’ to update configuration files.
