### ISSUE TITLE
papirus icon theme spkgbuild/pkgquery issue?

### ISSUE THREAD

**Issue by orkim** [venomlinux/ports#191]
An issue of the following command `pkgquery search papirus` will output the following:

```
(extra) $_name-light 20200102-1 Papirus icon theme (Light)
(extra) $_name-dark 20200102-1 Papirus icon theme (Dark)
(extra) papirus-icon-theme 20200102-1: Papirus icon theme
```

As you can see the first two are displayed wrong.  I'm not sure if this is with the spkgbuild for the ligtht/dark theme or if its a problem with pkgquery.  Looks like a variable is not getting evaluated between the `name=` and the `_name=` in the spkgbuild file.

If needed I can move to the venomlinux/scratchpkg project.

**Comment by emmett1** [comment]
Hey, thanks for the report. Looks like bugs from `scratchpkg` (`scratch` and `pkgquery`).
Now its fixed.
https://github.com/venomlinux/scratchpkg/commit/b6710e58c444337c4f09d54678e21c4dd3e04d9e
