### ISSUE TITLE
qt6-tools-6.4.0-1 fails

### ISSUE THREAD

**Issue by Pelle-B** [venomlinux/ports#2274]
`FAILED: src/linguist/lupdate/CMakeFiles/lupdate.dir/cpp_clang.cpp.o 
/usr/bin/ccache /usr/bin/c++ -DCINDEX_NO_EXPORTS -DLUPDATE_CLANG_VERSION_MAJOR=15 -DLUPDATE_CLANG_VERSION_MINOR=0 -DLUPDATE_CLANG_VERSION_PATCH=3 -DLUPDATE_CLANG_VERSION_STR=\"\"15.0.3\"\" -DQT_CORE_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_EXCEPTIONS -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_QMLINTEGRATION_LIB -DQT_QML_LIB -DQT_TOOLS_LIB -DQT_USE_QSTRINGBUILDER -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I/var/cache/scratchpkg/work/qt6-tools/src/build/src/linguist/lupdate/lupdate_autogen/include -I/var/cache/scratchpkg/work/qt6-tools/src/qttools-everywhere-src-6.4.0/src/linguist/lupdate -I/var/cache/scratchpkg/work/qt6-tools/src/build/src/linguist/lupdate -I/var/cache/scratchpkg/work/qt6-tools/src/qttools-everywhere-src-6.4.0/src/linguist/lupdate/../shared -I/var/cache/scratchpkg/work/qt6-tools/src/build/include -I/var/cache/scratchpkg/work/qt6-tools/src/build/include/QtTools -I/var/cache/scratchpkg/work/qt6-tools/src/qttools-everywhere-src-6.4.0/src/global -I/var/cache/scratchpkg/work/qt6-tools/src/build/src/global -I/var/cache/scratchpkg/work/qt6-tools/src/build/include/QtTools/6.4.0 -I/var/cache/scratchpkg/work/qt6-tools/src/build/include/QtTools/6.4.0/QtTools -isystem /usr/include/qt6/QtCore -isystem /usr/include/qt6 -isystem /usr/lib/qt6/mkspecs/linux-g++ -isystem /usr/include/qt6/QtCore/6.4.0 -isystem /usr/include/qt6/QtCore/6.4.0/QtCore -isystem /usr/include/qt6/QtQml/6.4.0 -isystem /usr/include/qt6/QtQml/6.4.0/QtQml -isystem /usr/include/qt6/QtQml -isystem /usr/include/qt6/QtQmlIntegration -isystem /usr/include/qt6/QtNetwork -O2 -march=x86-64 -pipe -march=x86-64 -pipe -O2 -fPIE -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -fno-exceptions -fPIC -Wsuggest-override -std=c++17 -MD -MT src/linguist/lupdate/CMakeFiles/lupdate.dir/cpp_clang.cpp.o -MF src/linguist/lupdate/CMakeFiles/lupdate.dir/cpp_clang.cpp.o.d -o src/linguist/lupdate/CMakeFiles/lupdate.dir/cpp_clang.cpp.o -c /var/cache/scratchpkg/work/qt6-tools/src/qttools-everywhere-src-6.4.0/src/linguist/lupdate/cpp_clang.cpp
In file included from /var/cache/scratchpkg/work/qt6-tools/src/qttools-everywhere-src-6.4.0/src/linguist/lupdate/cpp_clang.cpp:7:
/var/cache/scratchpkg/work/qt6-tools/src/qttools-everywhere-src-6.4.0/src/linguist/lupdate/lupdatepreprocessoraction.h:52:10: error: 'void LupdatePPCallbacks::InclusionDirective(clang::SourceLocation, const clang::Token&, llvm::StringRef, bool, clang::CharSourceRange, const clang::FileEntry*, llvm::StringRef, llvm::StringRef, const clang::Module*, clang::SrcMgr::CharacteristicKind)' marked 'override', but does not override
   52 |     void InclusionDirective(clang::SourceLocation /*hashLoc*/, const clang::Token &/*includeTok*/,
      |          ^~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
==> ERROR: Build failed: qt6-tools-6.4.0-1
`

I tried twice, I did run revdep inbetween.

**Comment by Visone-Selektah** [comment]
Hi!
I just send an update to fix build with clang

Thanks!!

**Comment by Pelle-B** [comment]
It works, Iclose the issue. Thanks!
