### ISSUE TITLE
can't install ttf-noto port

### ISSUE THREAD

**Issue by unbrand** [venomlinux/ports#2509]
I could successfully install ttf-noto-emoji, but when trying to install ttf-noto there's some kind of checksum problem? I get 

==> Building: ttf-noto-20220810-1
==> Source found: /var/cache/scratchpkg/sources/ttf-noto-20220810.tar.gz
==> Checking checksums...
 -> missing: be7ff4387da75831d54fe4e88f1882f7  noto-fonts-20201226.tar.gz
 -> new    : d9b05dfe616f125d46a65e8b75f4acb9  ttf-noto-20220810.tar.gz

???

**Comment by lumarogit** [comment]
Hi, port updated and fixed. Sync ports and try again. Thanks !
