### ISSUE TITLE
main/ffmpeg needs nv-codec-headers as dependancy for cuda

### ISSUE THREAD

**Issue by Ouaille-Aime-Scier** [venomlinux/ports#3148]
Please add nv-codec-headers as dependancy for ffmpeg.

**Comment by ghost** [comment]
it is an optional dependency. ffmpeg by itself don't need nv-codec-headers

**Comment by Deecellar** [comment]
We can add it the same way we add optional dependencies in others, add it to non free and see if it's installed to build ffmpeg acordingly
