### ISSUE TITLE
main/atril building fails

### ISSUE THREAD

**Issue by Ouaille-Aime-Scier** [venomlinux/ports#3149]
`ImportError:`` /usr/lib/python2.7/site-packages/libxml2mod.so: undefined symbol: xmlHandleEntity, version LIBXML2_2.4.30`

see build.log attached.
[build.log](https://github.com/venomlinux/ports/files/10288953/build.log)

**Comment by ghost** [comment]
It needs somthing like [this](https://github.com/venomlinux/ports/commit/7ba4e1c7cea4119058b15bf4d547f9042c5ce656) but python2 is no longer supported so its better remove /usr/bin/python /usr/bin/python-config and use a symbolic link of python3

**Comment by Visone-Selektah** [comment]
Hi!
I just build atril without problems, no python2 errors.
Check if you still have some python2 libraries in 
`/usr/lib/python2.7/` and remove it. 
run a revdep to check if you have some errors cause python2 and rebuild those pkgs

**Comment by Ouaille-Aime-Scier** [comment]
thanks, I remove last python2 packages on my system and atril's rebuilding went fine.
