### ISSUE TITLE
Port request 

### ISSUE THREAD

**Issue by ghost** [venomlinux/ports#3179]
Hi, would it be possible to port the Palemoon Web Browser and Docker (together with the relative service)? Thanks in advance.

**Comment by Visone-Selektah** [comment]
The last release of Palemoon remove the blockers support, so we change palemoon to basilisk, same fork but sill support blockers.
About docker, you have podman in repos, anyway, I'll see if a can port it to venom

**Comment by ghost** [comment]
@Visone-Selektah thanks so much, docker and Docker-compose would be important because i would like to run the privacy metasearch engine SearXNG and running it via docker at boot.
