### ISSUE TITLE
main/btrfs-progs-6.2-1 building fails with undefined macros

### ISSUE THREAD

**Issue by Ouaille-Aime-Scier** [venomlinux/ports#4047]
==> Building: btrfs-progs-6.2-1
==> Source found: /var/cache/scratchpkg/sources/btrfs-progs-v6.2.tar.xz
==> Checking checksums...
==> Unpacking: /var/cache/scratchpkg/sources/btrfs-progs-v6.2.tar.xz
==> Build start: btrfs-progs-6.2-1
+ build
+ cd btrfs-progs-v6.2
+ autoreconf -fv
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: /usr/bin/autoconf --force
configure.ac:7: error: possibly undefined macro: AC_DEFINE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:51: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:255: error: possibly undefined macro: AC_MSG_WARN
autoreconf: error: /usr/bin/autoconf failed with exit status: 1
==> ERROR: Build failed: btrfs-progs-6.2-1

**Comment by lumarogit** [comment]
Hi, sync ports and try again.  Updated build with autogen.sh, thanks !

**Comment by Ouaille-Aime-Scier** [comment]
thanks @lumarogit I will upgrade my system this evening.

**Comment by Ouaille-Aime-Scier** [comment]
I have new type of error with 6.2-2 version : 

`crypto/blake2b-round.h:34:5: error: type mismatch in conditional expression   34 |     : (-(c) == 63) ? mm_xor_si128(_mm_srli_epi64((x), -(c)), _mm_add_epi64((x), (x)))`

You can see same bug in Funtoo : [https://bugs.funtoo.org/browse/FL-11059](url)

**Comment by lumarogit** [comment]
Hi, edit the line 

"cp config.h.in include/"

with 

"./autogen.sh"

and test if it build fine. With "autogen.sh" it seems to build correctly in all cases. Crux use it too, share:

https://crux.nu/gitweb/?p=ports/opt.git;a=commitdiff;h=e90a66bca9b4ff76425d3c12c355938d618dea0f

**Comment by Ouaille-Aime-Scier** [comment]
> Hi, edit the line
> 
> "cp config.h.in include/"
> 
> with
> 
> "./autogen.sh"
> 
> and test if it build fine. With "autogen.sh" it seems to build correctly in all cases. Crux use it too, share:
> 
> https://crux.nu/gitweb/?p=ports/opt.git;a=commitdiff;h=e90a66bca9b4ff76425d3c12c355938d618dea0f

Ok I will replace cp config.h.in include/ with ./autogen.sh and try to build the package later thanks @lumarogit

**Comment by Ouaille-Aime-Scier** [comment]
> > Hi, edit the line
> > "cp config.h.in include/"
> > with
> > "./autogen.sh"
> > and test if it build fine. With "autogen.sh" it seems to build correctly in all cases. Crux use it too, share:
> > https://crux.nu/gitweb/?p=ports/opt.git;a=commitdiff;h=e90a66bca9b4ff76425d3c12c355938d618dea0f
> 
> Ok I will replace cp config.h.in include/ with ./autogen.sh and try to build the package later thanks @lumarogit

Same issue when using ./autogen.sh :-(

**Comment by lumarogit** [comment]
Hi, try install updated 6.2.1 version and feedback. Thanks.

**Comment by Ouaille-Aime-Scier** [comment]
> Hi, try install updated 6.2.1 version and feedback. Thanks.

Hello Luis, no more success, same build error with crypto module.

Daniel Robbins from Funtoo thinks btrfs-progs is synchronised with the Linux kernel, so btrfs-progs-6.2 is made for 6.2 kernel.

**Comment by lumarogit** [comment]
Hi, added blake patch, try again and feedback. Thanks.

**Comment by Ouaille-Aime-Scier** [comment]
> Hi, added blake patch, try again and feedback. Thanks.

Thanks Luis, this time all went fine when building btrf-progs !
