### ISSUE TITLE
Libressl : libssl.so.1.1 cannot open shared object file: no such file or directory

### ISSUE THREAD

**Issue by nenoro** [venomlinux/ports#4049]
Hello (New member of V.OS)

So i wanted to install libressl even changing the number of the version didn't fix the problem.
It fetches to get the archive but suddenly:

> curl: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

I don't want to continue with openssl, i really want to stick to libressl.

Is there a way to fix it ?

Edit: so basically i shouldn't have uninstalled openssl first to get libressl...

**Comment by ghost** [comment]
Try downloading https://curl.haxx.se/download/curl-7.88.1.tar.xz and moving `curl-7.88.1.tar.xz` to `/var/cache/scratchpkg/sources` (do the same with https://libarchive.org/downloads/libarchive-3.6.2.tar.xz) then move `/usr/bin/bsdtar` to a different place (`mv /usr/bin/bsdtar /usr/bin/bsdtar.bak`). After that run `ln -sf /bin/tar /usr/bsdtar` (it will replace bsdtar temporarly) now rebuild curl and libarchive with `scratch install -r curl libarchive`
