### ISSUE TITLE
Package: wine | Flag: outdated

### ISSUE THREAD

**Issue by doonoo** [venomlinux/ports#423]
The Package **wine** is outdated! 

@MalteKiefer @emmett1

wine supposed to be 6.2

**Comment by emmett1** [comment]
https://github.com/venomlinux/ports/commit/aab05ac12a0d9fd81677cf97c9bed49f37ee0b5a#diff-5abb5b99cca9cd5575663f15e4d4d9ed681c88104d25e6a74dadd3703bff234b
