### ISSUE TITLE
Package : Python3-3.9.1 revdep -r fails for libpeas

### ISSUE THREAD

**Issue by OuailleAimeScier** [venomlinux/ports#429]
After upgrading Python to 3.9.1 version, the revdep -r is generating libpeas package recompilation which fails due to default of prior rebuilding of these packages : meson, python3-setuptools, python3-gobject3 and gobject-introspection.

**Comment by emmett1** [comment]
Try run 'pkgfix -r'

**Comment by OuailleAimeScier** [comment]
Hi Emmett,

I have manually recompiled all the needed packages and all gone well. I note the pkgfix command for the next case thanks.

**Comment by emmett1** [comment]
Ok nice. btw, i'm planning on merge 'pkgfix' script with 'revdep'. so if later if 'pkgfix' not exist anymore, you know it merged.

**Comment by OuailleAimeScier** [comment]
> 
> 
> Ok nice. btw, i'm planning on merge 'pkgfix' script with 'revdep'. so if later if 'pkgfix' not exist anymore, you know it merged.

Ok thanks Emmett for merging these two maintenance tools !

**Comment by emmett1** [comment]
👍😊
