### ISSUE TITLE
miss `export` to set PYTHON environment variable

### ISSUE THREAD

**Issue by Dieken** [venomlinux/ports#4304]
https://github.com/venomlinux/ports/blob/fa34d7262507c4bf4dad788665ddf759963c2efe/main/itstool/spkgbuild#L11

Currently `/usr/bin/itstool` uses "#!/usr/bin/python -s" which points to Python 2,  but Venom Linux has only `python3-libxml2`.

**Comment by lumarogit** [comment]
Hi Dieken, fixed and merged. Thanks !
