### ISSUE TITLE
main/libatomic_ops-7.8.0 wrong source url

### ISSUE THREAD

**Issue by Ouaille-Aime-Scier** [venomlinux/ports#4376]
the source url for libatomic_ops-7.8.0 is
`https://github.com/ivmai/$name/releases/download/v$version/$name-$version.tar.gz`

**Comment by lumarogit** [comment]
Hi! You can download from "tags" or "releases", no problem, both are valid:

$name-$version.tar.gz::https://github.com/ivmai/libatomic_ops/archive/v${version}.tar.gz

https://github.com/ivmai/libatomic_ops/releases/download/v$version/$name-$version.tar.gz

Thanks !
