### ISSUE TITLE
question about runit

### ISSUE THREAD

**Issue by whoizit** [venomlinux/ports#467]
I can't see anything about runit on site venomlinux.org
but in wiki i can see this post https://github.com/venomlinux/ports/wiki/Managing-Runit

it says: `runit is the default init for Venom Linux`, but I can't see runit in base rootfs tarball.

what is the status of runit for this distro?

**Comment by emmett1** [comment]
VenomLinux already dropped completely runit, now it use bsd-style init based on sysvinit. Sorry wiki hasnt been updated for a while. Will delete post about runit.
