### ISSUE TITLE
Package: file-roller | Flag: broken

### ISSUE THREAD

**Issue by ghost** [venomlinux/ports#469]
The package **file-roller** is broken!

---------------------------------------
[75/75] Linking target src/file-roller
FAILED: src/file-roller 
cc  -o src/file-roller src/file-roller.p/meson-generated_.._fr-resources.c.o src/file-roller.p/meson-generated_.._fr-marshal.c.o src/file-roller.p/meson-generated_.._fr-enum-types.c.o src/file-roller.p/dlg-add.c.o src/file-roller.p/dlg-ask-password.c.o src/file-roller.p/dlg-batch-add.c.o src/file-roller.p/dlg-delete.c.o src/file-roller.p/dlg-extract.c.o src/file-roller.p/dlg-open-with.c.o src/file-roller.p/dlg-package-installer.c.o src/file-roller.p/dlg-password.c.o src/file-roller.p/dlg-prop.c.o src/file-roller.p/dlg-update.c.o src/file-roller.p/eggtreemultidnd.c.o src/file-roller.p/file-data.c.o src/file-roller.p/file-utils.c.o src/file-roller.p/fr-application.c.o src/file-roller.p/fr-application-menu.c.o src/file-roller.p/fr-archive.c.o src/file-roller.p/fr-command-7z.c.o src/file-roller.p/fr-command-ace.c.o src/file-roller.p/fr-command-alz.c.o src/file-roller.p/fr-command-ar.c.o src/file-roller.p/fr-command-arj.c.o src/file-roller.p/fr-command.c.o src/file-roller.p/fr-command-cfile.c.o src/file-roller.p/fr-command-cpio.c.o src/file-roller.p/fr-command-dpkg.c.o src/file-roller.p/fr-command-iso.c.o src/file-roller.p/fr-command-jar.c.o src/file-roller.p/fr-command-lha.c.o src/file-roller.p/fr-command-lrzip.c.o src/file-roller.p/fr-command-rar.c.o src/file-roller.p/fr-command-rpm.c.o src/file-roller.p/fr-command-tar.c.o src/file-roller.p/fr-command-unsquashfs.c.o src/file-roller.p/fr-command-unstuff.c.o src/file-roller.p/fr-command-zip.c.o src/file-roller.p/fr-command-zoo.c.o src/file-roller.p/fr-error.c.o src/file-roller.p/fr-file-selector-dialog.c.o src/file-roller.p/fr-init.c.o src/file-roller.p/fr-list-model.c.o src/file-roller.p/fr-location-bar.c.o src/file-roller.p/fr-new-archive-dialog.c.o src/file-roller.p/fr-process.c.o src/file-roller.p/fr-window-actions-callbacks.c.o src/file-roller.p/fr-window.c.o src/file-roller.p/gio-utils.c.o src/file-roller.p/glib-utils.c.o src/file-roller.p/gth-icon-cache.c.o src/file-roller.p/gtk-utils.c.o src/file-roller.p/java-utils.c.o src/file-roller.p/main.c.o src/file-roller.p/open-file.c.o src/file-roller.p/preferences.c.o src/file-roller.p/rar-utils.c.o src/file-roller.p/fr-archive-libarchive.c.o -Wl,--as-needed -Wl,--no-undefined -O2 -march=x86-64 -pipe -Wl,--start-group -lm -pthread /usr/lib/libglib-2.0.so /usr/lib/libgthread-2.0.so /usr/lib/libgtk-3.so /usr/lib/libgdk-3.so /usr/lib/libpangocairo-1.0.so /usr/lib/libpango-1.0.so /usr/lib/libharfbuzz.so /usr/lib/libatk-1.0.so /usr/lib/libcairo-gobject.so /usr/lib/libcairo.so /usr/lib/libgdk_pixbuf-2.0.so /usr/lib/libgio-2.0.so /usr/lib/libgobject-2.0.so /usr/lib/libnotify.so /usr/lib/libarchive.so -Wl,--end-group
/usr/bin/ld: src/file-roller.p/fr-init.c.o:/var/cache/scratchpkg/work/file-roller/src/file-roller-3.32.3/build/../src/fr-init.c:197: multiple definition of `ForceDirectoryCreation'; src/file-roller.p/fr-application.c.o:/var/cache/scratchpkg/work/file-roller/src/file-roller-3.32.3/build/../src/fr-application.c:45: first defined here
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
==> ERROR: Build 'file-roller-3.32.3-1' failed.

---------------------------------------

@MalteKiefer @emmett1

**Comment by emmett1** [comment]
`file-roller` is in testing repo and not well maintained. I will try look into it on my free time.

**Comment by lumarogit** [comment]
This issue is quite old, if you are still interested in the port, you can open a new one.
