### ISSUE TITLE
rust, rust-bin, librsvg

### ISSUE THREAD

**Issue by temp987349867934876** [venomlinux/ports#470]
Please consider shipping a rust binary like gentoo does.

After 6 hours of compiling rust source code fails with no space left.
All for just one library named librsvg.

Only thing I can do is to download librsvg from pkgs.org or copy it over from my other linuxes.

Thx

**Comment by emmett1** [comment]
`rust-bin` port has been added https://github.com/venomlinux/ports/commit/bbf383ba1c6b07e81d76000714d2bdf2b10d7cbf

make an alias for `rust` to `rust-bin` by running:
`echo "rust rust-bin" >> /etc/scratchpkg.alias`
so any ports depends on `rust` scratch will pull `rust-bin` instead.
