### ISSUE TITLE
Package: mpv | Flag: broken

### ISSUE THREAD

**Issue by temp987349867934876** [venomlinux/ports#471]
The package mpv is broken!

[233/233] Linking build/mpv
/usr/bin/ld: warning: libx265.so.188, needed by /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib/libavcodec.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib/libavcodec.so: undefined reference to `x265_api_get_188'
collect2: error: ld returned 1 exit status

Waf: Leaving directory `/var/cache/scratchpkg/work/mpv/src/mpv-0.33.1/build'
Build failed
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)
==> ERROR: Build 'mpv-0.33.1-1' failed.

**Comment by MalteKiefer** [comment]
Since no response from user, issue will be closed

**Comment by temp987349867934876** [comment]
Working now (after doing a revdep -r), thank you
