### ISSUE TITLE
No sound in system

### ISSUE THREAD

**Issue by mubharad** [venomlinux/ports#477]
Starting pipewire and pipewire-pulse gives following error

>>> [W][000000177.055234][module-rtkit.c:182 translate_error()] RTKit error: org.freedesktop.DBus.Error.ServiceUnknown
[W][000000177.055278][module-rtkit.c:516 set_nice()] could not set nice-level to -11: No such file or directory
[W][000000177.055587][module-rtkit.c:182 translate_error()] RTKit error: org.freedesktop.DBus.Error.ServiceUnknown
[W][000000177.055791][module-rtkit.c:182 translate_error()] RTKit error: org.freedesktop.DBus.Error.ServiceUnknown
[W][000000177.055989][module-rtkit.c:182 translate_error()] RTKit error: org.freedesktop.DBus.Error.ServiceUnknown
[W][000000177.055999][module-rtkit.c:503 idle_func()] could not make thread realtime: No such file or directory

I have pipewire and pipewire-pulse packages installed. Am i missing something else or need to enable any other service?

Thanks.

**Comment by emmett1** [comment]
Not sure about pipewire. Have you tried unmute using alsamixer?

**Comment by lumarogit** [comment]
This issue is quite old and without a response from the author, I close it.
