### ISSUE TITLE
gmp libgmp issue

### ISSUE THREAD

**Issue by temp987349867934876** [venomlinux/ports#478]
install: libgmp-6.2.1-1...
usr/lib/libgmp.so.10
usr/lib/libgmp.so.10.4.1
usr/lib/libgmpxx.so
usr/lib/libgmpxx.so.4
usr/lib/libgmpxx.so.4.6.1
usr/lib/pkgconfig/gmpxx.pc
usr/lib/pkgconfig/gmp.pc
usr/lib/libgmp.so
usr/share/info/gmp.info.gz
usr/share/info/gmp.info-1.gz
usr/share/info/gmp.info-2.gz
usr/include/gmpxx.h
usr/include/gmp.h
==> ERROR: File conflict found!

As a result I cannot upgrade scratchpkg and gcc and cannot make a sysup.

PS:
A --force switch would help...
Just deleting the claimed files doesnt help: Scratch needs them.
I tried to edit the index to fake an install after copying the extracted files over, but that didnt work either

**Comment by temp987349867934876** [comment]
--ignore-conflict ...

**Comment by emmett1** [comment]
Please install latest release (2.0).
