### ISSUE TITLE
fetch_rootfs() The requested URL returned error: 404

### ISSUE THREAD

**Issue by vcatafesta** [venomlinux/ports#4798]
fetch_rootfs()

sudo ./scripts/build.sh -fetch
-> Fetching rootfs tarball: https://github.com/venomlinux/ports/releases/download/vrolling/venomlinux-rootfs-rolling-x86_64.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     9    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
!> Error fetching rootfs tarball

**Comment by emmett1** [comment]
fixed https://github.com/venomlinux/ports/commit/01afe74024e76b6e02429ddc0a1ce6d31425d5f2
