### ISSUE TITLE
Package: libmpfr | Flag: broken

### ISSUE THREAD

**Issue by temp987349867934876** [venomlinux/ports#485]
The package **libmpfr** is broken!

---------------------------------------
Continue install package(s)? (Y/n) 

==> Building: libmpfr-4.1.0-1
==> Source found: /var/cache/scratchpkg/sources/mpfr-4.1.0.tar.xz
==> Checking checksums...
==> Unpacking: /var/cache/scratchpkg/sources/mpfr-4.1.0.tar.xz
==> Build start: libmpfr-4.1.0-1
+ build
+ cd libmpfr-4.1.0
/usr/bin/pkgbuild: 10: cd: can't cd to libmpfr-4.1.0
==> ERROR: Build failed: libmpfr-4.1.0-1

---------------------------------------

@MalteKiefer @emmett1

**Comment by emmett1** [comment]
https://github.com/venomlinux/ports/commit/3266c3642f15de76d059bd0d4fce597a9e84a4bd
