### ISSUE TITLE
dino: missing dependencies

### ISSUE THREAD

**Issue by mobinmob** [venomlinux/ports#4867]
dino spkgbuild misses at least dependencies for `gtk4`, `libadwaita` (cannot build without them) and `gnutls`.

**Comment by lumarogit** [comment]
Fixed and merged !!! Thanks !!!

https://github.com/venomlinux/ports/pull/4868/commits/9ac992f75bfc22b7a2f0e680bf7d14dd5cc4009e

**Comment by mobinmob** [comment]
Thanx for the fix!.
