### ISSUE TITLE
alsa-lib 1.2.5-1 breaks sound

### ISSUE THREAD

**Issue by Pelle-B** [venomlinux/ports#488]
`aplay clock.wav
ALSA lib confmisc.c:855:(parse_card) cannot find card '0dmix:0'
ALSA lib conf.c:5088:(_snd_config_evaluate) function snd_func_card_id returned error: No such device
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5088:(_snd_config_evaluate) function snd_func_concat returned error: No such device
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5088:(_snd_config_evaluate) function snd_func_refer returned error: No such device
ALSA lib conf.c:5576:(snd_config_expand) Evaluate error: No such device
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM dmix:0dmix:0
aplay: main:852: audio open error: No such device
`
No errors after a clean installation or live USB-stick, errors occur after update. 
00:14.2 Audio device: Advanced Micro Devices, Inc. [AMD] FCH Azalia Controller (rev 01)
01:00.1 Audio device: NVIDIA Corporation GK208 HDMI/DP Audio Controller (rev a1)

`cat /proc/asound/cards
 0 [Generic        ]: HDA-Intel - HD-Audio Generic
                      HD-Audio Generic at 0xfe300000 irq 16
 1 [NVidia         ]: HDA-Intel - HDA NVidia
                      HDA NVidia at 0xfe080000 irq 42
`

**Comment by emmett1** [comment]
https://github.com/venomlinux/ports/commit/27d9f6020e37e2c13b69f181a5a213180280c08c
added patch. Can you check is it fixed?

**Comment by Pelle-B** [comment]
Yes, now sound works without any issues. I did not really understand how to download the patch, but edited the files in question.

**Comment by emmett1** [comment]
Actually you just need to update the system.

`sudo portsync && sudo scratch sysup`

**Comment by Pelle-B** [comment]
I needed to change version to 2.1 too. The error messages at boot time remain, unfortunatedly I can not figure out in which logfile to find them.

**Comment by emmett1** [comment]
Yes the boot time error still remain for me too but sound works fine. If you wanna use old version you can manually change port to 1.2.4 then build and install it. Then add `alsa-lib` to `/etc/scratchpkg.mask` to avoid from sysup.

**Comment by Pelle-B** [comment]
As long as I can not hear the errors it is no problem! If you consider them unimportant, just leave them there. Thanks for your efforts!
