### ISSUE TITLE
Package : grub-efi-2.06 compilation fails

### ISSUE THREAD

**Issue by OuailleAimeScier** [venomlinux/ports#489]
When compiling grub-efi-2.06, I got this error with gcc flag : 
``/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/include/shaintrin.h:40:1: error: SSE register return with SSE disabled``

**Comment by emmett1** [comment]
Try comment `CFLAGS` and `CXXFLAGS` in `/etc/scratchpkg.conf` and rebuild.

**Comment by OuailleAimeScier** [comment]
Hi Emmett,

The compilation works fine when commenting the CFLAGS and CXXFLAGS in scratchpkg.conf thanks for your help.
