### ISSUE TITLE
Imagemagick

### ISSUE THREAD

**Issue by SleepBag123** [venomlinux/ports#492]
Imagemagick has some mirror problems
`curl: (22) The requested URL returned error: 404
==> ERROR: Fetching failed: https://www.imagemagick.org/download/ImageMagick-7.0.11-14.tar.xz
`

**Comment by SleepBag123** [comment]
I know this is not a internet problem because I can compile it from source there is some problem in the mirror because going to the link shows 404

**Comment by emmett1** [comment]
yeah imagemagick7 always problematic when fetching from upstream. upstream delete old source after releasing new version. this error will happen when i'm late updating the port after upstream make new release.
i will try search some alternative to avoid this in the future.
