### ISSUE TITLE
Request Djvulibre

### ISSUE THREAD

**Issue by Pelle-B** [venomlinux/ports#493]
Djviewer (4.12) and runtime (3.5.28)

To make Firefox find djviewer, the executable must be called djview4 or have a symlink of that name.

**Comment by emmett1** [comment]
this one? http://djvu.sourceforge.net/djview4.html

**Comment by Pelle-B** [comment]
Yes. I forgot to include the link. Sorry about that.

**Comment by lumarogit** [comment]
This issue is quite old, if you are still interested in the port, you can open a new one.
