### ISSUE TITLE
Installation fails if a file (icons, appdefaults etc) already exists

### ISSUE THREAD

**Issue by Pelle-B** [venomlinux/ports#494]
It goes like
`usr/share/icons/hicolor/16x16/apps/libreoffice7.1-writer.png
usr/share/icons/hicolor/16x16/apps/libreoffice7.1-calc.png
==> ERROR: File conflict found!`

If the files are removed, installation works.

**Comment by emmett1** [comment]
on which package? libreoffice?

**Comment by Pelle-B** [comment]
All packages. If an iconfile with the same name is already in place, same with /etc/X11/appdefaults

**Comment by emmett1** [comment]
ofcourse if file already in place it will conflict. `scratchpkg` (also with most package manager exist) does not allow multiple packages provide same file. you should not install files into system outside package manager, it can cause this conflict error.
