### ISSUE TITLE
Build custom RootFS?

### ISSUE THREAD

**Issue by ghost** [venomlinux/ports#4944]
How do I build a custom RootFS? It seems the current build.sh script just downloads a RootFS from the web and patches it. Is there a way to generate a whole new RootFS?

**Comment by Visone-Selektah** [comment]
Hi!
Check makerootfs.sh in scripts directory

**Comment by ghost** [comment]
> Hi! Check makerootfs.sh in scripts directory

When i run the script i get
```
!> invalid options: -rootfs\
```
and running `build.sh -zap -rebase -rootfs` still tries to fetch the rootfs from the website
```
-> Fetching rootfs tarball: https://github.com/venomlinux/ports/releases/download/20230527/venomlinux-rootfs-x86_64.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  1  192M    1 3072k    0     0  4083k      0  0:00:48 --:--:--  0:00:48 4083k
  ```
  the problem is i want to generate a rootfs from scratch

**Comment by Visone-Selektah** [comment]
Hi!  
Sorry 4 the dealy!!

There's no option to do that automatically with the scripts, but I guess you can do something like this:
1.- Download rootfs, and extracted.
2.- Get into it using `build.sh -chroot`
3.- Do whatever you want to do
4.- Run manually the function `compress_rootfs` from `build.sh` script
