### ISSUE TITLE
qtwebengine fails to build

### ISSUE THREAD

**Issue by ghost** [venomlinux/ports#496]
[4717/18360] CXX obj/base/i18n/string_compare.o
FAILED: obj/base/i18n/string_compare.o 
/usr/bin/g++ -MMD -MF obj/base/i18n/string_compare.o.d -DBASE_I18N_IMPLEMENTATION -DUSE_UDEV -DUSE_AURA=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DOFFICIAL_BUILD -DTOOLKIT_QT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DUSING_SYSTEM_ICU=1 -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_STATIC -DUCHAR_TYPE=uint16_t -Igen -I../../../../src/3rdparty/chromium -Igen -Igen -Igen -I../../../../src/3rdparty/chromium/third_party/ced/src -I../../../../src/3rdparty/chromium/third_party/boringssl/src/include -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pipe -pthread -m64 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -fno-delete-null-pointer-checks -Wno-comments -Wno-packed-not-aligned -Wno-dangling-else -Wno-missing-field-initializers -Wno-unused-parameter -fno-omit-frame-pointer -g0 -fvisibility=hidden -O2 -fno-ident -fdata-sections -ffunction-sections -std=gnu++14 -Wno-narrowing -Wno-class-memaccess -Wno-attributes -Wno-class-memaccess -Wno-subobject-linkage -Wno-invalid-offsetof -Wno-return-type -Wno-deprecated-copy -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -c ../../../../src/3rdparty/chromium/base/i18n/string_compare.cc -o obj/base/i18n/string_compare.o
../../../../src/3rdparty/chromium/base/i18n/string_compare.cc: In function 'UCollationResult base::i18n::CompareString16WithCollator(const icu_68::Collator&, base::StringPiece16, base::StringPiece16)':
../../../../src/3rdparty/chromium/base/i18n/string_compare.cc:21:26: error: 'FALSE' was not declared in this scope
   21 |       icu::UnicodeString(FALSE, lhs.data(), static_cast<int>(lhs.length())),
      |                          ^~~~~
[4718/18360] CXX obj/base/i18n/string_search.o
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile.gn_run:550: run_ninja] Error 1
make[3]: Leaving directory '/var/cache/scratchpkg/work/qtwebengine/src/qtwebengine-everywhere-src-5.15.1/build/src/core'
make[2]: *** [Makefile:82: sub-gn_run-pro-make_first] Error 2
make[2]: Leaving directory '/var/cache/scratchpkg/work/qtwebengine/src/qtwebengine-everywhere-src-5.15.1/build/src/core'
make[1]: *** [Makefile:80: sub-core-make_first] Error 2
make[1]: Leaving directory '/var/cache/scratchpkg/work/qtwebengine/src/qtwebengine-everywhere-src-5.15.1/build/src'
make: *** [Makefile:49: sub-src-make_first] Error 2
==> ERROR: Build failed: qtwebengine-5.15.1-1

**Comment by temp987349867934876** [comment]
need it for otter-browser
(or qtwebkit, but this fails at checking checksums)

**Comment by Pelle-B** [comment]
I ran into the same problem. It is needed also for python3-pyqt5 .

**Comment by emmett1** [comment]
https://github.com/venomlinux/ports/commit/1e2e86f4658e8ec2e712d7bbfa9e4cc6685a73f3
updated to `5.15.2`, build fine for me. i hope it fixed for you guys too.

**Comment by Pelle-B** [comment]
I got
`[4321/20765] ACTION //third_party/devt...src-5.15.2/build/src/toolchain:target)
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile.gn_run:550: run_ninja] Error 1
make[3]: Leaving directory '/var/cache/scratchpkg/work/qtwebengine/src/qtwebengine-everywhere-src-5.15.2/build/src/core'
make[2]: *** [Makefile:82: sub-gn_run-pro-make_first] Error 2
make[2]: Leaving directory '/var/cache/scratchpkg/work/qtwebengine/src/qtwebengine-everywhere-src-5.15.2/build/src/core'
make[1]: *** [Makefile:80: sub-core-make_first] Error 2
make[1]: Leaving directory '/var/cache/scratchpkg/work/qtwebengine/src/qtwebengine-everywhere-src-5.15.2/build/src'
make: *** [Makefile:49: sub-src-make_first] Error 2
==> ERROR: Build failed: qtwebengine-5.15.2-1
`

**Comment by emmett1** [comment]
Can you give longer log details?

Btw are you sure your system clean from any broken packages?
`revdep -r`

**Comment by Pelle-B** [comment]
No broken packages. I will do a little experiment with the order of installing dependencies and report after that.

**Comment by Pelle-B** [comment]
I tried to install all the dependencies first, no broken packages, and then I got
`
[4008/20765] CXX obj/third_party/crash...hpad/util/util/http_transport_socket.o                                                
In file included from /usr/include/string.h:519,                                                                               
                 from /usr/include/c++/10.3.0/cstring:42,                                                                      
                 from ../../../../src/3rdparty/chromium/base/logging.h:12,                                                     
                 from ../../../../src/3rdparty/chromium/base/stl_util.h:26,                                                    
                 from ../../../../src/3rdparty/chromium/base/files/file_path.h:1                                               14,                                                                                         
                 from ../../../../src/3rdparty/chromium/third_party/crashpad/cra                                               shpad/util/net/http_transport.h:21,                                                                                            
                 from ../../../../src/3rdparty/chromium/third_party/crashpad/cra                                               shpad/util/net/http_transport_socket.cc:15:                                                                                    
In function 'char* strncpy(char*, const char*, size_t)',                                                                       
    inlined from 'bool crashpad::{anonymous}::WriteRequest(crashpad::{anonymous}                                               ::Stream*, const string&, const string&, const HTTPHeaders&, crashpad::HTTPBodyS                                               tream*)' at ../../../../src/3rdparty/chromium/third_party/crashpad/crashpad/util                                               /net/http_transport_socket.cc:403:14:
/usr/include/bits/string_fortified.h:95:34: warning: 'char* __builtin_strncpy(char*, const char*, long unsigned int)' output may be truncated copying 8 bytes from a string of length 8 [-Wstringop-truncation]
   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
   96 |       __glibc_objsize (__dest));
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~   
[4318/20765] CXX obj/base/i18n/string_compare.o
FAILED: obj/base/i18n/string_compare.o 
/usr/bin/g++ -MMD -MF obj/base/i18n/string_compare.o.d -DBASE_I18N_IMPLEMENTATION -DUSE_UDEV -DUSE_AURA=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DOFFICIAL_BUILD -DTOOLKIT_QT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DUSING_SYSTEM_ICU=1 -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_STATIC -DUCHAR_TYPE=uint16_t -Igen -I../../../../src/3rdparty/chromium -Igen -Igen -Igen -I../../../../src/3rdparty/chromium/third_party/ced/src -I../../../../src/3rdparty/chromium/third_party/boringssl/src/include -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pipe -pthread -m64 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -fno-delete-null-pointer-checks -Wno-comments -Wno-packed-not-aligned -Wno-dangling-else -Wno-missing-field-initializers -Wno-unused-parameter -fno-omit-frame-pointer -g0 -fvisibility=hidden -O2 -fno-ident -fdata-sections -ffunction-sections -std=gnu++14 -Wno-narrowing -Wno-class-memaccess -Wno-attributes -Wno-class-memaccess -Wno-subobject-linkage -Wno-invalid-offsetof -Wno-return-type -Wno-deprecated-copy -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -c ../../../../src/3rdparty/chromium/base/i18n/string_compare.cc -o obj/base/i18n/string_compare.o
../../../../src/3rdparty/chromium/base/i18n/string_compare.cc: In function 'UCollationResult base::i18n::CompareString16WithCollator(const icu_68::Collator&, base::StringPiece16, base::StringPiece16)':
../../../../src/3rdparty/chromium/base/i18n/string_compare.cc:21:26: error: 'FALSE' was not declared in this scope
   21 |       icu::UnicodeString(FALSE, lhs.data(), static_cast<int>(lhs.length())),
      |                          ^~~~~
`

**Comment by temp987349867934876** [comment]
i think it does not change anything

[4169/20743] CXX obj/base/i18n/string_compare.o
FAILED: obj/base/i18n/string_compare.o 
/usr/bin/g++ -MMD -MF obj/base/i18n/string_compare.o.d -DBASE_I18N_IMPLEMENTATION -DUSE_UDEV -DUSE_AURA=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DOFFICIAL_BUILD -DTOOLKIT_QT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DUSING_SYSTEM_ICU=1 -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_STATIC -DUCHAR_TYPE=uint16_t -Igen -I../../../../src/3rdparty/chromium -Igen -Igen -Igen -I../../../../src/3rdparty/chromium/third_party/ced/src -I../../../../src/3rdparty/chromium/third_party/boringssl/src/include -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pipe -pthread -m64 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -fno-delete-null-pointer-checks -Wno-comments -Wno-packed-not-aligned -Wno-dangling-else -Wno-missing-field-initializers -Wno-unused-parameter -fno-omit-frame-pointer -g0 -fvisibility=hidden -O2 -fno-ident -fdata-sections -ffunction-sections -std=gnu++14 -Wno-narrowing -Wno-class-memaccess -Wno-attributes -Wno-class-memaccess -Wno-subobject-linkage -Wno-invalid-offsetof -Wno-return-type -Wno-deprecated-copy -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -c ../../../../src/3rdparty/chromium/base/i18n/string_compare.cc -o obj/base/i18n/string_compare.o
../../../../src/3rdparty/chromium/base/i18n/string_compare.cc: In function 'UCollationResult base::i18n::CompareString16WithCollator(const icu_68::Collator&, base::StringPiece16, base::StringPiece16)':
../../../../src/3rdparty/chromium/base/i18n/string_compare.cc:21:26: error: 'FALSE' was not declared in this scope
   21 |       icu::UnicodeString(FALSE, lhs.data(), static_cast<int>(lhs.length())),
      |                          ^~~~~
[4170/20743] CXX obj/base/i18n/string_search.o
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile.gn_run:550: run_ninja] Error 1
make[3]: Leaving directory '/var/cache/scratchpkg/work/qtwebengine/src/qtwebengine-everywhere-src-5.15.2/build/src/core'
make[2]: *** [Makefile:82: sub-gn_run-pro-make_first] Error 2
make[2]: Leaving directory '/var/cache/scratchpkg/work/qtwebengine/src/qtwebengine-everywhere-src-5.15.2/build/src/core'
make[1]: *** [Makefile:80: sub-core-make_first] Error 2
make[1]: Leaving directory '/var/cache/scratchpkg/work/qtwebengine/src/qtwebengine-everywhere-src-5.15.2/build/src'
make: *** [Makefile:49: sub-src-make_first] Error 2
==> ERROR: Build failed: qtwebengine-5.15.2-1
