### ISSUE TITLE
Request sneedacity

### ISSUE THREAD

**Issue by UltraSmurfsforever** [venomlinux/ports#497]
A fork of audacity without the spooky stuff

**Comment by emmett1** [comment]
You should give me the correct url for the project too

**Comment by UltraSmurfsforever** [comment]
Ok

**Comment by UltraSmurfsforever** [comment]
https://github.com/Sneeds-Feed-and-Seed/sneedacity

**Comment by emmett1** [comment]
Alright, i'm already on it but found issue. It required `wxgtk 3.1.x` which is version `3.0.x` already in the repo required by `filezilla`. Those two version could conflict.

**Comment by Pelle-B** [comment]
Does Filezilla not compile and run with the higher version of wxgtk?

**Comment by Menelkir** [comment]
Not meaning to hijack this request, but I think tenacity is a better fork: https://github.com/tenacityteam/tenacity

**Comment by lumarogit** [comment]
This issue is quite old, if you are still interested in the port, you can open a new one.
