### ISSUE TITLE
Request lutris

### ISSUE THREAD

**Issue by Menelkir** [venomlinux/ports#499]
Lutris is somehow a frontend of wine, but able to manage and download different wine versions, dxvk and support many other things that makes the use of wine easier.

https://lutris.net/
https://github.com/lutris/lutris

**Comment by Menelkir** [comment]
I saw lutris (at least on arch and gentoo, for that matter) casts gnome-desktop. I will see if it's possible to patch this out in the next days. I'll close this until then.

**Comment by emmett1** [comment]
Yeah, i already try to port this but stuck with gnome dependency, so i'm hold it for now. Maybe will try again if gnome can be skipped.
