### ISSUE TITLE
portsync does not sync

### ISSUE THREAD

**Issue by Pelle-B** [venomlinux/ports#500]
I have httpup installed, repositories are set to
https://raw.githubusercontent.com/venomlinux/ports/2.1/main/
https://raw.githubusercontent.com/venomlinux/ports/2.1/nonfree/
https://raw.githubusercontent.com/venomlinux/ports/2.1/testing/

It says it has finished updating succesfully, but the new and updated packages can not be found. Same problem on two different installations.

**Comment by emmett1** [comment]
`portsync` now use git to sync repo. Please change repo to `https://github.com/venomlinux/ports/tree/2.1/main` url. Same goes to multilib and nonfree repo.

**Comment by Pelle-B** [comment]
I suspected that it was something like that.  It works now. Thanks!
