### ISSUE TITLE
libzip as dependency for tldr

### ISSUE THREAD

**Issue by Spacefreak18** [venomlinux/ports#5000]
the tldr package needs libzip added as a compile time dependency

**Comment by ghost** [comment]
I think we don't have a var to add 'compile time packages'. anyways you can add a scratch install libzip and uninstalli it at the end of the spkgbuild. but I don't think that's the best way to do it

**Comment by Spacefreak18** [comment]
the dependencies at the top of the spkgbuild are the dependencies, and that is where libzip is needed.

**Comment by ghost** [comment]
> the dependencies at the top of the spkgbuild are the dependencies, and that is where libzip is needed.

but libzip is already there check https://github.com/venomlinux/ports/blob/repos/main/tldr/spkgbuild

**Comment by Spacefreak18** [comment]
that's bizarre, i installed it today and i swear it wouldn't compile because it was missing libzip, i manually installed libzip, then it obviously worked fine.

I didn't even bother to check obviously. I'll do some tests if i have time to see if there is something wrong about the format of the file. I think I'm the one that actually wrote that spkgbuild.
