### ISSUE TITLE
alsa service does not start on runit

### ISSUE THREAD

**Issue by ghost** [venomlinux/ports#5022]
After a fresh install of the runit version I can't change the volume levels with alsamixer. No matter what I set, the level will always bounce back to default. I have always noticed that the alsa service is not running and it won't be started manually. Btw, my user is also part of the audio group. I have not had the time to dvelve deeper but the sysv version works on the same PC.

**Comment by Visone-Selektah** [comment]
Hi!
Did you check if it's actually runing?
` sv status alsa`
Anyway, you can save the actual state of alsamixer with `alsactl store`

**Comment by ghost** [comment]
Yes, I checked, it's down, wanted up. If I try to start it manually, it does not. Alsamixer shows the right device but the volume levels can't be changed.

**Comment by Visone-Selektah** [comment]
Send a fix for the service file, check if it works.

**Comment by ghost** [comment]
Great, currently I have the sysV version installed, I will try to install the runit version when the bug with the EFI partition is fixed 👍
