### ISSUE TITLE
New installer always formatting the EFI partition

### ISSUE THREAD

**Issue by ghost** [venomlinux/ports#5025]
I have noticed that the new iso asks for the EFI partition and whether you want to install grub or not, the way it always did. However, it does not ask anymore whether you want to format the EFi partition or not. So, if you have some other bootloader like, say, rEFInd, the installer will erase it and some users wouldn't want that.

**Comment by Visone-Selektah** [comment]
Hi!!
It's fixed, you can check with any on the la later isos
