### ISSUE TITLE
[bug: ports 2.1] i3-gaps build failed

### ISSUE THREAD

**Issue by damon-kwok** [venomlinux/ports#508]
```sh
scratch install i3-gaps i3blocks i3blocks i3lock i3status -y
...
../meson.build:128:60: ERROR: Program or command '[' not found or not executable
...
```
-details:
[i3-gaps.log](https://github.com/venomlinux/ports/files/7244289/i3-gaps.log)

**Comment by emmett1** [comment]
are you sure your system is up-to-date? this '[' should be solved already [here](https://github.com/venomlinux/ports/commit/c38ebc5d3409d1595038974128c4e5757a34efa0)

**Comment by damon-kwok** [comment]
yes, my port is up-to date-

**Comment by damon-kwok** [comment]
@emmett1 
```sh
scratch sync
scratch upgrade scratchpkg
Package 'scratchpkg' is  up to date.
scratch install i3-gaps'

../meson.build:128:60: ERROR: Program or command '[' not found or not executable

```

**Comment by emmett1** [comment]
Hmm ok. Try rebuild 'coreutils'. `scratch build -f coreutils && scratch install -r coreutils`

**Comment by damon-kwok** [comment]
```sh
scratch build -f coreutils && scratch install -r coreutils
scratch install i3-gaps'

../meson.build:128:60: ERROR: Program or command '[' not found or not executable
```

**Comment by emmett1** [comment]
For this i will check later after work. I think it bugs from scratchpkg. It cant read '[' then remove it from system after upgrading.

**Comment by damon-kwok** [comment]
Any update?

**Comment by emmett1** [comment]
Yes its already fixed. Make sure system is up to date
