### ISSUE TITLE
Port requests (some programms for work)

### ISSUE THREAD

**Issue by pkg1-byte** [venomlinux/ports#516]
Hey how it going? I need some software for work and etc. It would be great if you ported it's.
qTox - client for chating by Tox
Virt-Manager - GUI for qemu
LibreCAD - a program for working with drawings, 2D projects, etc...
Blender, FreeCAD, OpensCAD - programs for 3D modeling
XFCE lacks some components, for example xfce4-pulseaudio-plugin, and some more: I won't describe exactly, but you can't reboot or turn off the system through the GUI
Thank you very much.

**Comment by lumarogit** [comment]
This issue is quite old, if you are still interested in the port, you can open a new one.
