### ISSUE TITLE
Fails to boot

### ISSUE THREAD

**Issue by scsijon** [venomlinux/ports#518]
New 3.0-rc1 on a dell optiplex 745 minibase

from start of boot
>
Probing EDD (edd=off to disable)... ok
[    0.333891] x86/cpu: VMX (outside TXT) disabled by BIOS
:: running earlyhook: udev
:: running earlyhook: venomiso
:: wait for media device ...
:: media is not appeared even after wait for 5 seconds...
:: try increase wait time by append 'wait=<seconds>' to boot cmdline

>

I've tried adding wait=30 and 300, no differance
also tried adding edd=off, but it seems the commandline only allows one addition, it ignores a second one
let me know if you want a hardinfo hardware report and i'll create and add it.
Any ideas folks?
Thought i'd try it as it is non-systemd/elongd as a base, but if it can't run it's not worth continuing with it.
ps I've also downloaded and tried 2.1 with the same results, you got  problem somewhere.
pps Also i take it what you call a port is adding a new package, that means I will need to add about 20, but no problem, it would be nice to be able to build as individual packages though so there is no need to build each time.
ppps attached report
>

Devices
*******

Processor
---------

-Processors-
Intel(R) Core(TM)2 Duo CPU     E6550  @ 2.33GHz		: 2188.81MHz
Intel(R) Core(TM)2 Duo CPU     E6550  @ 2.33GHz		: 2289.28MHz

Memory
------

-Memory-
Total Memory		: 3907424 kB
Free Memory		: 2099428 kB
MemAvailable		: 2598856 kB
Buffers		: 35688 kB
Cached		: 665692 kB
Cached Swap		: 0 kB
Active		: 1326616 kB
Inactive		: 406764 kB
Active(anon)		: 1049000 kB
Inactive(anon)		: 149840 kB
Active(file)		: 277616 kB
Inactive(file)		: 256924 kB
Unevictable		: 0 kB
Mlocked		: 0 kB
Virtual Memory		: 33554428 kB
Free Virtual Memory		: 33554428 kB
Dirty		: 76 kB
Writeback		: 0 kB
AnonPages		: 1031996 kB
Mapped		: 294376 kB
Shmem		: 166844 kB
Slab		: 37248 kB
SReclaimable		: 19700 kB
SUnreclaim		: 17548 kB
KernelStack		: 3744 kB
PageTables		: 11712 kB
NFS_Unstable		: 0 kB
Bounce		: 0 kB
WritebackTmp		: 0 kB
CommitLimit		: 35508140 kB
Committed_AS		: 1664760 kB
VmallocTotal		: 34359738367 kB
VmallocUsed		: 0 kB
VmallocChunk		: 0 kB
DirectMap4k		: 60412 kB
DirectMap2M		: 3991552 kB

PCI Devices
-----------

-PCI Devices-
Host bridge		: Intel Corporation 82Q35 Express DRAM Controller (rev 02)
VGA compatible controller		: Intel Corporation 82Q35 Express Integrated Graphics Controller (rev 02) (prog-if 00 [VGA controller])
Display controller		: Intel Corporation 82Q35 Express Integrated Graphics Controller (rev 02)
Communication controller		: Intel Corporation 82Q35 Express MEI Controller (rev 02)
IDE interface		: Intel Corporation 82Q35 Express PT IDER Controller (rev 02) (prog-if 85 [Master SecO PriO])
Serial controller		: Intel Corporation 82Q35 Express Serial KT Controller (rev 02) (prog-if 02 [16550])
USB controller		: Intel Corporation 82801I (ICH9 Family) USB UHCI Controller #4 (rev 02) (prog-if 00 [UHCI])
USB controller		: Intel Corporation 82801I (ICH9 Family) USB UHCI Controller #5 (rev 02) (prog-if 00 [UHCI])
USB controller		: Intel Corporation 82801I (ICH9 Family) USB2 EHCI Controller #2 (rev 02) (prog-if 20 [EHCI])
Audio device		: Intel Corporation 82801I (ICH9 Family) HD Audio Controller (rev 02)
PCI bridge		: Intel Corporation 82801I (ICH9 Family) PCI Express Port 1 (rev 02) (prog-if 00 [Normal decode])
USB controller		: Intel Corporation 82801I (ICH9 Family) USB UHCI Controller #1 (rev 02) (prog-if 00 [UHCI])
USB controller		: Intel Corporation 82801I (ICH9 Family) USB UHCI Controller #2 (rev 02) (prog-if 00 [UHCI])
USB controller		: Intel Corporation 82801I (ICH9 Family) USB UHCI Controller #3 (rev 02) (prog-if 00 [UHCI])
USB controller		: Intel Corporation 82801I (ICH9 Family) USB2 EHCI Controller #1 (rev 02) (prog-if 20 [EHCI])
PCI bridge		: Intel Corporation 82801 PCI Bridge (rev 92) (prog-if 01 [Subtractive decode])
ISA bridge		: Intel Corporation 82801IO (ICH9DO) LPC Interface Controller (rev 02)
SATA controller		: Intel Corporation 82801IR/IO/IH (ICH9R/DO/DH) 6 port SATA Controller [AHCI mode] (rev 02) (prog-if 01 [AHCI 1.0])
SMBus		: Intel Corporation 82801I (ICH9 Family) SMBus Controller (rev 02)

USB Devices
-----------

-USB Devices-
Linux Foundation 2.0 root hub
Linux Foundation 1.1 root hub
Linux Foundation 1.1 root hub
Linux Foundation 1.1 root hub
Samsung Electronics Co., Ltd GT-I9500 (Galaxy S4) / GT-I9250 (Galaxy Nexus) (network tethering)
Linux Foundation 2.0 root hub
Linux Foundation 1.1 root hub
Hewlett-Packard KU-0316 Keyboard
Logitech, Inc. M105 Optical Mouse
Linux Foundation 1.1 root hub

Printers
--------

-Printers (CUPS)-
CUPS-PDF
HP_OfficeJet_Pro_7740_series		: <i>Default</i>

Battery
-------

-No batteries-
No batteries found on this system

Sensors
-------

Input Devices
-------------

-Input Devices-
 Logitech USB Optical Mouse
 CHICONY HP Basic USB Keyboard
 Power Button
 Power Button
 PC Speaker
 HDA Digital PCBeep
 HDA Intel Mic
 HDA Intel Line
 HDA Intel Line Out
 HDA Intel Front Headphone

Storage
-------

-SCSI Disks-
ATA ST2000DM001-1E61
HL-DT-ST DVD+-RW GSA-T21N

DMI
---

-BIOS-
Date		: 03/11/2008
Vendor		: Dell Inc. (Dell Computer, www.dell.com)
Version		: A09
-Board-
Name		: 0HX555
Vendor		: Dell Inc. (Dell Computer, www.dell.com)

Memory SPD
----------

-SPD-
Please load the eeprom module to obtain information about memory SPD

Resources
---------

-I/O Ports-
<tt>0000-0cf7 </tt>		: PCI Bus 0000:00
<tt>  0000-001f </tt>		: dma1
<tt>  0020-0021 </tt>		: pic1
<tt>  0040-0043 </tt>		: timer0
<tt>  0050-0053 </tt>		: timer1
<tt>  0060-0060 </tt>		: keyboard
<tt>  0061-0061 </tt>		: PNP0800:00
<tt>  0064-0064 </tt>		: keyboard
<tt>  0070-007f </tt>		: rtc0
<tt>  0080-008f </tt>		: dma page reg
<tt>  00a0-00a1 </tt>		: pic2
<tt>  00c0-00df </tt>		: dma2
<tt>  00f0-00ff </tt>		: PNP0C04:00
<tt>    00f0-00ff </tt>		: fpu
<tt>  0378-037a </tt>		: parport0
<tt>  037b-037f </tt>		: parport0
<tt>  03c0-03df </tt>		: vga+
<tt>  03f8-03ff </tt>		: serial
<tt>  0800-087f </tt>		: <b><small>PCI</small></b>  Intel Corporation 82801IO (ICH9DO) LPC Interface Controller (rev 02)
<tt>    0800-0803 </tt>		: ACPI PM1a_EVT_BLK
<tt>    0804-0805 </tt>		: ACPI PM1a_CNT_BLK
<tt>    0808-080b </tt>		: ACPI PM_TMR
<tt>    0820-082f </tt>		: ACPI GPE0_BLK
<tt>    0830-0833 </tt>		: iTCO_wdt.0.auto
<tt>    0860-087f </tt>		: iTCO_wdt.0.auto
<tt>  0880-08bf </tt>		: <b><small>PCI</small></b>  Intel Corporation 82801IO (ICH9DO) LPC Interface Controller (rev 02)
<tt>  0c00-0c7f </tt>		: pnp 00:00
<tt>0cf8-0cff </tt>		: PCI conf1
<tt>0d00-ffff </tt>		: PCI Bus 0000:00
<tt>  1000-1fff </tt>		: PCI Bus 0000:01
<tt>  ecb0-ecb7 </tt>		: <b><small>PCI</small></b>  Intel Corporation 82Q35 Express Integrated Graphics Controller (rev 02) (prog-if 00 [VGA controller])
<tt>  ecb8-ecbf </tt>		: <b><small>PCI</small></b>  Intel Corporation 82Q35 Express Serial KT Controller (rev 02) (prog-if 02 [16550])
<tt>    ecb8-ecbf </tt>		: serial
<tt>  ece0-ecff </tt>		: <b><small>PCI</small></b>  Intel Corporation 82801I (ICH9 Family) SMBus Controller (rev 02)
<tt>    ece0-ecff </tt>		: i801_smbus
<tt>  fe00-fe07 </tt>		: <b><small>PCI</small></b>  Intel Corporation 82801IR/IO/IH (ICH9R/DO/DH) 6 port SATA Controller [AHCI mode] (rev 02) (prog-if 01 [AHCI 1.0])
<tt>    fe00-fe07 </tt>		: ahci
<tt>  fe10-fe13 </tt>		: <b><small>PCI</small></b>  Intel Corporation 82801IR/IO/IH (ICH9R/DO/DH) 6 port SATA Controller [AHCI mode] (rev 02) (prog-if 01 [AHCI 1.0])
<tt>    fe10-fe13 </tt>		: ahci
<tt>  fe20-fe27 </tt>		: <b><small>PCI</small></b>  Intel Corporation 82801IR/IO/IH (ICH9R/DO/DH) 6 port SATA Controller [AHCI mode] (rev 02) (prog-if 01 [AHCI 1.0])
<tt>    fe20-fe27 </tt>		: ahci
<tt>  fe30-fe33 </tt>		: <b><small>PCI</small></b>  Intel Corporation 82801IR/IO/IH (ICH9R/DO/DH) 6 port SATA Controller [AHCI mode] (rev 02) (prog-if 01 [AHCI 1.0])
<tt>    fe30-fe33 </tt>		: ahci
<tt>  fe80-fe87 </tt>		: <b><small>PCI</small></b>  Intel Corporation 82Q35 Express PT IDER Controller (rev 02) (prog-if 85 [Master SecO PriO])
<tt>    fe80-fe87 </tt>		: ata_generic
<tt>  fe90-fe93 </tt>		: <b><small>PCI</small></b>  Intel Corporation 82Q35 Express PT IDER Controller (rev 02) (prog-if 85 [Master SecO PriO])
<tt>    fe90-fe93 </tt>		: ata_generic
<tt>  fea0-fea7 </tt>		: <b><small>PCI</small></b>  Intel Corporation 82Q35 Express PT IDER Controller (rev 02) (prog-if 85 [Master SecO PriO])
<tt>    fea0-fea7 </tt>		: ata_generic
<tt>  feb0-feb3 </tt>		: <b><small>PCI</small></b>  Intel Corporation 82Q35 Express PT IDER Controller (rev 02) (prog-if 85 [Master SecO PriO])
<tt>    feb0-feb3 </tt>		: ata_generic
<tt>  fec0-fedf </tt>		: <b><small>PCI</small></b>  Intel Corporation 82801IR/IO/IH (ICH9R/DO/DH) 6 port SATA Controller [AHCI mode] (rev 02) (prog-if 01 [AHCI 1.0])
<tt>    fec0-fedf </tt>		: ahci
<tt>  fef0-feff </tt>		: <b><small>PCI</small></b>  Intel Corporation 82Q35 Express PT IDER Controller (rev 02) (prog-if 85 [Master SecO PriO])
<tt>    fef0-feff </tt>		: ata_generic
<tt>  ff00-ff1f </tt>		: <b><small>PCI</small></b>  Intel Corporation 82801I (ICH9 Family) USB UHCI Controller #5 (rev 02) (prog-if 00 [UHCI])
<tt>    ff00-ff1f </tt>		: uhci_hcd
<tt>  ff20-ff3f </tt>		: <b><small>PCI</small></b>  Intel Corporation 82801I (ICH9 Family) USB UHCI Controller #4 (rev 02) (prog-if 00 [UHCI])
<tt>    ff20-ff3f </tt>		: uhci_hcd
<tt>  ff40-ff5f </tt>		: <b><small>PCI</small></b>  Intel Corporation 82801I (ICH9 Family) USB UHCI Controller #3 (rev 02) (prog-if 00 [UHCI])
<tt>    ff40-ff5f </tt>		: uhci_hcd
<tt>  ff60-ff7f </tt>		: <b><small>PCI</small></b>  Intel Corporation 82801I (ICH9 Family) USB UHCI Controller #2 (rev 02) (prog-if 00 [UHCI])
<tt>    ff60-ff7f </tt>		: uhci_hcd
<tt>  ff80-ff9f </tt>		: <b><small>PCI</small></b>  Intel Corporation 82801I (ICH9 Family) USB UHCI Controller #1 (rev 02) (prog-if 00 [UHCI])
<tt>    ff80-ff9f </tt>		: uhci_hcd
-Memory-
<tt>00000000-00000fff </tt>		: Reserved
<tt>00001000-0009e3ff </tt>		: System RAM
<tt>0009e400-0009ffff </tt>		: RAM buffer
<tt>000a0000-000bffff </tt>		: PCI Bus 0000:00
<tt>000c0000-000effff </tt>		: PCI Bus 0000:00
<tt>  000c0000-000c7fff </tt>		: Video ROM
<tt>000f0000-000fffff </tt>		: PCI Bus 0000:00
<tt>  000f0000-000fffff </tt>		: Reserved
<tt>    000f0000-000fffff </tt>		: System ROM
<tt>00100000-cf4ff7ff </tt>		: System RAM
<tt>  01000000-018031f0 </tt>		: Kernel code
<tt>  018031f1-01e96b7f </tt>		: Kernel data
<tt>  02146000-02199fff </tt>		: Kernel bss
<tt>cf4ff800-cf553bff </tt>		: ACPI Non-volatile Storage
<tt>cf553c00-cf555bff </tt>		: ACPI Tables
<tt>cf555c00-dfffffff </tt>		: Reserved
<tt>  cf600000-dfffffff </tt>		: PCI Bus 0000:00
<tt>    cf800000-cfffffff </tt>		: Graphics Stolen Memory
<tt>    d0000000-dfffffff </tt>		: <b><small>PCI</small></b>  Intel Corporation 82Q35 Express Integrated Graphics Controller (rev 02) (prog-if 00 [VGA controller])
<tt>e0000000-efffffff </tt>		: Reserved
<tt>f0000000-fed003ff </tt>		: Reserved
<tt>  f0000000-fec00000 </tt>		: PCI Bus 0000:00
<tt>    f0000000-f01fffff </tt>		: PCI Bus 0000:01
<tt>    f0200000-f02007ff </tt>		: <b><small>PCI</small></b>  Intel Corporation 82801IR/IO/IH (ICH9R/DO/DH) 6 port SATA Controller [AHCI mode] (rev 02) (prog-if 01 [AHCI 1.0])
<tt>      f0200000-f02007ff </tt>		: ahci
<tt>    f0200800-f020080f </tt>		: <b><small>PCI</small></b>  Intel Corporation 82Q35 Express MEI Controller (rev 02)
<tt>    f0201000-f0201fff </tt>		: Intel Flush Page
<tt>    f0204000-f0207fff </tt>		: i915 MCHBAR
<tt>    fe800000-fe8fffff </tt>		: PCI Bus 0000:01
<tt>    fe9fab00-fe9fabff </tt>		: <b><small>PCI</small></b>  Intel Corporation 82801I (ICH9 Family) SMBus Controller (rev 02)
<tt>    fe9fac00-fe9fafff </tt>		: <b><small>PCI</small></b>  Intel Corporation 82801I (ICH9 Family) USB2 EHCI Controller #2 (rev 02) (prog-if 20 [EHCI])
<tt>      fe9fac00-fe9fafff </tt>		: ehci_hcd
<tt>    fe9fb000-fe9fbfff </tt>		: <b><small>PCI</small></b>  Intel Corporation 82Q35 Express Serial KT Controller (rev 02) (prog-if 02 [16550])
<tt>    fe9fc000-fe9fffff </tt>		: <b><small>PCI</small></b>  Intel Corporation 82801I (ICH9 Family) HD Audio Controller (rev 02)
<tt>      fe9fc000-fe9fffff </tt>		: ICH HD audio
<tt>    fea00000-fea7ffff </tt>		: <b><small>PCI</small></b>  Intel Corporation 82Q35 Express Integrated Graphics Controller (rev 02) (prog-if 00 [VGA controller])
<tt>    fea80000-feafffff </tt>		: <b><small>PCI</small></b>  Intel Corporation 82Q35 Express Integrated Graphics Controller (rev 02)
<tt>    feb00000-febfffff </tt>		: <b><small>PCI</small></b>  Intel Corporation 82Q35 Express Integrated Graphics Controller (rev 02) (prog-if 00 [VGA controller])
<tt>  fed00000-fed003ff </tt>		: HPET 0
<tt>    fed00000-fed003ff </tt>		: PNP0103:00
<tt>fed20000-fed9ffff </tt>		: Reserved
<tt>  fed20000-fed9ffff </tt>		: PCI Bus 0000:00
<tt>fedab410-fedab414 </tt>		: iTCO_wdt.0.auto
<tt>fedad800-fedadfff </tt>		: PCI Bus 0000:00
<tt>fee00000-feefffff </tt>		: Reserved
<tt>  fee00000-fee00fff </tt>		: Local APIC
<tt>ff97c000-ff97ffff </tt>		: PCI Bus 0000:00
<tt>ff980800-ff980bff </tt>		: PCI Bus 0000:00
<tt>  ff980800-ff980bff </tt>		: <b><small>PCI</small></b>  Intel Corporation 82801I (ICH9 Family) USB2 EHCI Controller #1 (rev 02) (prog-if 20 [EHCI])
<tt>    ff980800-ff980bff </tt>		: ehci_hcd
<tt>ffb00000-ffffffff </tt>		: Reserved
<tt>100000000-127ffffff </tt>		: System RAM
-DMA-
<tt> 4</tt>		: cascade

>

**Comment by scsijon** [comment]
I've been trying out a 3.0rc1 dvd burn on a number of machines as time and access has alloweded, across both desktop and notebook and a number of brands available here in australia. It seems that the problem is that your DVD only seems to allow UEFI booting, it can't handle either bios only or if secure boot has been turned off. As most of my 'modern' boxes have secure boot off and older are bios only, I believe you can consider it a problem that needs fixing.

**Comment by Pelle-B** [comment]
No problem with booting here,  this includes a usually troublesome Imac from 2008 (I think), an even older Packard-Bell laptop with BIOS, a Lenovo laptop with Radeon GPU from 2018, and a Lenovo desktop with NVIDIA from 2016. RC1 boots into an usuable system (with X).

If you used the same disc all the time, the solution is obvious, burn another one or use an USB memory stick. It seems very unlikely that boot would fail on all machines you tried if the medium was OK.

**Comment by scsijon** [comment]
Thanks for the reply, but...

Sorry, but i've tried that. I've even got past that to the point of 
downloading a new copy and burnt a dvd on a different brand dvd from on 
a different systems burner. Same fails and error points on the same 
failing systems, frustrating!

It's nice to see it works for someone though. I just need to work out 
what's wrong.

I shall persevere and see what else I can find that may be causing it, 
as the further I 'get into it' the more I like it's abilities and 
posabilities.

**Comment by emmett1** [comment]
Maybe venom's kernel not detect some of your hardware. If you familiar with kernel compiling, try install venom using tarball then compile your own kernel.

**Comment by scsijon** [comment]
Thank you, hadn't though of that one, i'll look at a copy of your kernel 
config file and see what's different wrt my normal puppy/easyos kernel 
config one.

I wonder if enough is being loaded that a  "|dmesg | grep -i 
firmware"||will work, I will give it a go in a few hours when I am free 
and reply here.|

|
|
|Buy the way you should be using either a 5.10.xx (LTS), or 5.14.xx / 
5.15.1 kernels, 5.12.xx was shutoff EOL due to svn's.
|
|
|
||On 9/11/21 13:28, Emmett1 wrote:
> Maybe venom's kernel not detect some of your hardware. If you familiar with kernel compiling, try install venom using tarball then compile your own kernel.
>

**Comment by Pelle-B** [comment]
The only "issue" I had, and that on all four computers, is that I get a message from Modem Manager that it can not find a driver for some PCI, then the output stops, I hit enter and login shows up. When I have logged in X starts.

The messages (two in a row) read
ModemManager[485]<info> [base-manager]couldn't check support for device '/sys/devices/pci[snip, too many digits for me after work':not supported by any plugin

After logging in manually and X is started, there is an error message `ERROR:openbox-xdg-autostart requires PYXDG to be installed`

The kernel seems to be 5.10.71-Venom-LTS.

I have just been booting the live system from an USB-stick, checked if the system seemed to work, then moved on to try the next computer, and then gone off to work.

**Comment by scsijon** [comment]
thanks Pelle-B for the reply

I wonder which pyxdg it wants as there are a few of them and they are 
not interchangeable.

OK, at least it means it relates to my end systems with the problem 
cause. The kernel config file is vastly different to what we use with 
puppylinux too, I had a quick look, it will take some time to sort the 
changes out and find the missing or unwanted 'switch'.

The kernel version I mentioned above was a note for emmett1 as the one 
listed in the current port is 5.12.1.

**Comment by scsijon** [comment]
OK, i'm closing it with the warning and a note that it looks like your kernel config hasn't set it to handle my series of processors. Maybe something to look at in the future if it reocurrs
