### ISSUE TITLE
Description on Sourceforge probably needs an update

### ISSUE THREAD

**Issue by Pelle-B** [venomlinux/ports#522]
[https://sourceforge.net/projects/venomlinux/files/3.0/](url)

The following does not seem to be valid any more.

`System configuration
--------------------
Edit /etc/runit/runit.conf to configure timezone, clock, font and keymap.
Installation using the iso should configured this already.

Services
---------------
services script is placed in /etc/sv/ directory.
enabling service is by make a symlink from /etc/sv/<service> to /var/service
disabling service is by removing symlink created in /var/service`

**Comment by lumarogit** [comment]
This issue is quite old, it is currently Venom 4.0, I close it. Thanks.
