### ISSUE TITLE
How do I build my own version of venom?

### ISSUE THREAD

**Issue by scsijon** [venomlinux/ports#552]
Read all the doccumentation and quite a bit of the scripts and can't see how to build a customised venom from scratch.

I admit i'm use to building packages and creating a system from there.

I can see how to build individual packages and a complete venom system, but not how to customise it to my requirements with a packagelist to build.

Am I missing something somewhere?

**Comment by Spacefreak18** [comment]
i'm sorry, i'm not sure what you mean.

After you've gotten a basic system up and running with chroot, you can install whatever you want. For example, I have a list of packages in my dotfiles, that I would just tell scratch to install.

If you have a custom port repo, you can put that in /etc/scratchpkg.repo, at the top so it overrides packages in the default repo.

**Comment by Deecellar** [comment]
https://venomlinux.org/wiki#create-custom-iso.introduction - Deals with how to create a custom iso

Also in the wiki section on this repo

**Comment by scsijon** [comment]
Decellar, that link just gives me a blank page, nothing on it.

Spacefreak18, I'm after a specific set with built packages to use in a container, not a whole onepiece-system. I thought from the past that it could still do this, or has it degraded to only building a complete system.

**Comment by Spacefreak18** [comment]
you can  also create a "meta-port" which is just a spkgbuild with a bunch of dependencies that you want to install

**Comment by scsijon** [comment]
I'm going to try a few things with a copy of venom to see if I can get it to supply what I need. i'll close this as the replies seem to at least give me a clue to work with. Thank you all.
