### ISSUE TITLE
wiki - writing ports?

### ISSUE THREAD

**Issue by scsijon** [venomlinux/ports#553]
As a preliminary while awaiting an answer to #552 i'd start to port packages we use but you haven't already in venom anywhere as I've got a dozen or so packages to port to start with if were going to use venomlinux as a quirky or easyos base. 

I started writing a new port as a trial for ZIM-Wiki, a smart desktop wiki that i use constantly, and reading and re-reading the writing ports doccument has left me a bit confused. 

The initial problem relates to your doccument saying under spkgbuild format >

    Note: The port's name must be lower-case and cannot contain spaces or hyphens (-). Using sed to correct this is common.

And yet it looks like you do this already in the names of a number of packages, such as alsa-plugins, appstream-glib and ca-certificates just to mention three, or am i missreading the doccument?

thanks

**Comment by lumarogit** [comment]
Hi, check this link.
https://venomlinux.org/wiki#writing-port.writing-ports

This issue is quite old, I close it and if you decide to continue, you can always open another one. Thanks.
