### ISSUE TITLE
RTL8821CE module not working

### ISSUE THREAD

**Issue by Pelle-B** [venomlinux/ports#555]
I  had to add dkms and get a module from[https://github.com/tomaspinho/rtl8821ce](url) to be able to connect to wifi on a Lenovo Ideapad 330

**Comment by Visone-Selektah** [comment]
Still need that pkg? If I'm not wrong that driver it's already in the kernel

**Comment by Pelle-B** [comment]
I personally do not need it, but maybe somebody else does. That laptop is a bit slow for Venom, so I dropped it.

**Comment by Visone-Selektah** [comment]
I asked cause I have that chip and it works otb in every distro.
Anyway, I'll try with the iso to test it.
Thanks!!!

**Comment by Pelle-B** [comment]
I have not had any problems with other distros either. I posted this in February, there has been some updates since then.
