### ISSUE TITLE
expat / libexpat has a security problem pre 2.4.6 and needs updating

### ISSUE THREAD

**Issue by scsijon** [venomlinux/ports#562]
it's also moving to https://github.com/libexpat/libexpat

**Comment by emmett1** [comment]
Alright, will take a look at it later after work.

**Comment by emmett1** [comment]
https://github.com/venomlinux/ports/commit/a7d8ed99fa826cab5ae4bde30b5a4374b914d7ea

**Comment by scsijon** [comment]
ty
