### ISSUE TITLE
rust fails compiling

### ISSUE THREAD

**Issue by ifys** [venomlinux/ports#564]
tried several times unable to update rust

**Comment by Spacefreak18** [comment]
what's the error message look like?

**Comment by ifys** [comment]
Traceback (most recent call last):
  File "/var/cache/scratchpkg/work/rust/src/rustc-1.60.0-src/./x.py", line 27, in <module>
    bootstrap.main()
  File "/var/cache/scratchpkg/work/rust/src/rustc-1.60.0-src/src/bootstrap/bootstrap.py", line 1325, in main
    bootstrap(help_triggered)
  File "/var/cache/scratchpkg/work/rust/src/rustc-1.60.0-src/src/bootstrap/bootstrap.py", line 1311, in bootstrap
    run(args, env=env, verbose=build.verbose, is_bootstrap=True)
  File "/var/cache/scratchpkg/work/rust/src/rustc-1.60.0-src/src/bootstrap/bootstrap.py", line 185, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /var/cache/scratchpkg/work/rust/src/rustc-1.60.0-src/build/bootstrap/debug/bootstrap install -v
==> ERROR: Build failed: rust-1.60.0-1

________________________________

**Comment by emmett1** [comment]
Can you give longer error log?

**Comment by ifys** [comment]
cro-backtrace -Ctarget-feature=-crt-static -Ztls-model=initial-exec -Z binary-dep-depinfo -L native=/var/cache/scratchpkg/work/rust/src/rustc-1.60.0-src/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/build/lzma-sys-6c49a4478d4d6301/out` (exit status: 101)
command did not execute successfully: "/var/cache/scratchpkg/work/rust/src/rustc-1.60.0-src/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "-Zbinary-dep-depinfo" "-j" "8" "-v" "--release" "--locked" "--frozen" "--manifest-path" "/var/cache/scratchpkg/work/rust/src/rustc-1.60.0-src/src/tools/rust-installer/Cargo.toml" "--message-format" "json-render-diagnostics"
expected success, got: exit status: 101
Traceback (most recent call last):
  File "/var/cache/scratchpkg/work/rust/src/rustc-1.60.0-src/./x.py", line 27, in <module>
    bootstrap.main()
  File "/var/cache/scratchpkg/work/rust/src/rustc-1.60.0-src/src/bootstrap/bootstrap.py", line 1325, in main
    bootstrap(help_triggered)
  File "/var/cache/scratchpkg/work/rust/src/rustc-1.60.0-src/src/bootstrap/bootstrap.py", line 1311, in bootstrap
    run(args, env=env, verbose=build.verbose, is_bootstrap=True)
  File "/var/cache/scratchpkg/work/rust/src/rustc-1.60.0-src/src/bootstrap/bootstrap.py", line 185, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /var/cache/scratchpkg/work/rust/src/rustc-1.60.0-src/build/bootstrap/debug/bootstrap install -v
==> ERROR: Build failed: rust-1.60.0-1


is this fine ??
________________________________

**Comment by Pelle-B** [comment]
With 1.61 I get:

`
  13: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::                                                                               call_once                                                                                                           
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src                                                                               /ops/function.rs:259:13                                                                                                                                        
  14: std::panicking::try::do_call                                                                                                                             
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/                                                                               panicking.rs:492:40                                                                                                                                         
  15: std::panicking::try                                                                                                                                      
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/                                                                               panicking.rs:456:19                                                                                                                                         
  16: std::panic::catch_unwind                                                                                                                                 
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/                                                                               panic.rs:137:14                                                                                                                             
  17: std::rt::lang_start_internal::{{closure}}                                                                                                                
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/                                                                               rt.rs:128:48                                                                                                                    
  18: std::panicking::try::do_call                                                                                                                             
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  19: std::panicking::try
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  20: std::panic::catch_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  21: std::rt::lang_start_internal
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:20
  22: main
  23: <unknown>
  24: __libc_start_main
  25: _start
command did not execute successfully: "/var/cache/scratchpkg/work/rust/src/rustc-1.61.0-src/build/x86_64-unknown-linux-gnu/stage0-tools-bin/fabricate" "generate" "--image-dir" "/var/cache/scratchpkg/work/rust/src/rustc-1.61.0-src/build/tmp/tarball/rustc/x86_64-unknown-linux-gnu/image" "--component-name=rustc" "--rel-manifest-dir=rustlib" "--legacy-manifest-dirs=rustlib,cargo" "--product-name=Rust" "--success-message=rustc installed." "--package-name=rustc-1.61.0-x86_64-unknown-linux-gnu" "--non-installed-overlay" "/var/cache/scratchpkg/work/rust/src/rustc-1.61.0-src/build/tmp/tarball/rustc/x86_64-unknown-linux-gnu/overlay" "--output-dir" "/var/cache/scratchpkg/work/rust/src/rustc-1.61.0-src/build/dist" "--work-dir" "/var/cache/scratchpkg/work/rust/src/rustc-1.61.0-src/build/tmp/tarball/rustc/x86_64-unknown-linux-gnu"
expected success, got: exit status: 1


Traceback (most recent call last):
  File "/var/cache/scratchpkg/work/rust/src/rustc-1.61.0-src/./x.py", line 27, in <module>
    bootstrap.main()
  File "/var/cache/scratchpkg/work/rust/src/rustc-1.61.0-src/src/bootstrap/bootstrap.py", line 1324, in main
    bootstrap(help_triggered)
  File "/var/cache/scratchpkg/work/rust/src/rustc-1.61.0-src/src/bootstrap/bootstrap.py", line 1310, in bootstrap
    run(args, env=env, verbose=build.verbose, is_bootstrap=True)
  File "/var/cache/scratchpkg/work/rust/src/rustc-1.61.0-src/src/bootstrap/bootstrap.py", line 185, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /var/cache/scratchpkg/work/rust/src/rustc-1.61.0-src/build/bootstrap/debug/bootstrap install -v
==> ERROR: Build failed: rust-1.61.0-1`
