### ISSUE TITLE
Port Request: Tvheadend

### ISSUE THREAD

**Issue by kleytr6s** [venomlinux/ports#565]
tvheadend.org

Tvheadend is a TV streaming server and recorder for Linux, FreeBSD and Android supporting DVB-S, DVB-S2, DVB-C, DVB-T, DVB-T2, ATSC, ISDB-T, IPTV, SAT>IP and HDHomeRun as input sources.

Tvheadend offers the HTTP (VLC, MPlayer), HTSP (Kodi, Movian) and SAT>IP streaming.

Multiple EPG sources are supported (over-the-air DVB and ATSC including OpenTV DVB extensions, XMLTV, PyXML).

The Analog video (V4L) is supported directly up to version 3.4.
In recent version, the pipe:// source (in IPTV network) might be used to obtain the MPEG-TS stream generated by ffmpeg/libav from a V4L device.

The code is hosted at github https://github.com/tvheadend/tvheadend.
Please use github's features if you want to provide patches.

**Comment by ghost** [comment]
Im currently writen that package but what do you mean with
> The code is hosted at github https://github.com/tvheadend/tvheadend. Please use github's features if you want to provide patches.

btw if do you want to see some process or make suggestions here is the unfinished package https://github.com/AldairbotHerotaku/vur/tree/main/testing/tvheadend

**Comment by emmett1** [comment]
Looks good, you should add to main repos.

**Comment by kleytr6s** [comment]
> Im currently writen that package but what do you mean with
> 
> > The code is hosted at github https://github.com/tvheadend/tvheadend. Please use github's features if you want to provide patches.
> 
> btw if do you want to see some process or make suggestions here is the unfinished package https://github.com/AldairbotHerotaku/vur/tree/main/testing/tvheadend

That is a copy of their homepage.

**Comment by ghost** [comment]
> That is a copy of their homepage.

Ok it should be working but i don't used this program before so if you can test it for be sure that everything is working I would be very grateful

**Comment by kleytr6s** [comment]
I cannot test it due to the following error [https://github.com/venomlinux/venomlinux.org/issues/8](url)

**Comment by ghost** [comment]
This happened after install the package?

> I cannot test it due to the following error [https://github.com/venomlinux/venomlinux.org/issues/8](url)

**Comment by kleytr6s** [comment]
> This happened after install the package?
> 
> > I cannot test it due to the following error [https://github.com/venomlinux/venomlinux.org/issues/8](url)

No, it does not go past the error when testing the live image. I have not been able to load the OS to install the package.

**Comment by ghost** [comment]
> > This happened after install the package?
> > > I cannot test it due to the following error [https://github.com/venomlinux/venomlinux.org/issues/8](url)
> 
> No, it does not go past the error when testing the live image. I have not been able to load the OS to install the package.

I think that i found the problem. It doesn't boot because it can't find the partition for mount has root for some reason. (idk if is your case. anyways try booting Venom linux (debug) for have more info about it)

**Comment by kleytr6s** [comment]
It stops loading with the following error.  media is not appeared even after wait for 5 seconds... try increase wait time by append 'wait=<seconds> to boot cmdline
