### ISSUE TITLE
alsamixer volume wont change

### ISSUE THREAD

**Issue by daedhel** [venomlinux/ports#5689]
System installed from the iso.

In alsamixer, I can raise the "Master" level, but half a second after changing the level to the level it was when alsamixer was launched.

My system:

```
# uname -a
Linux tour 6.1.39-Venom-LTS #1 SMP PREEMPT_DYNAMIC Sat Jul 22 21:24:53 EDT 2023 x86_64 GNU/Linux
```

**Comment by ghost** [comment]
Have you tried to create a .asoundrc configuration file according to [this guide ](https://docs.voidlinux.org/config/media/alsa.html) ?
