### ISSUE TITLE
babl can not upgrade

### ISSUE THREAD

**Issue by Pelle-B** [venomlinux/ports#573]
`The Meson build system
Version: 0.62.0
Source dir: /var/cache/scratchpkg/work/babl/src/babl-0.1.92
Build dir: /var/cache/scratchpkg/work/babl/src/babl-0.1.92/builddir
Build type: native build
Project name: babl
Project version: 0.1.92
C compiler for the host machine: cc (gcc 11.2.0 "cc (Venom Linux 11.2.0-1) 11.2.0")
C linker for the host machine: cc ld.bfd 2.37
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (/usr/bin/python3)

../meson.build:58:5: ERROR: configuration_data.set10 got unknown keyword arguments "Description"

A full log can be found at /var/cache/scratchpkg/work/babl/src/babl-0.1.92/builddir/meson-logs/meson-log.txt
==> ERROR: Build failed: babl-0.1.92-1
`
 /var/cache/scratchpkg/work/babl/src/babl-0.1.92/builddir/meson-logs/meson-log.txt is missing

**Comment by emmett1** [comment]
try run 'sudo scratch build babl -w' then give me /var/cache/scratchpkg/work/babl/src/babl-0.1.92/builddir/meson-logs/meson-log.txt

**Comment by Pelle-B** [comment]
Build started at 2022-04-06T21:07:04.793794
Main binary: /usr/bin/python3
Build Options: -Dprefix=/usr
Python system: Linux
The Meson build system
Version: 0.62.0
Source dir: /var/cache/scratchpkg/work/babl/src/babl-0.1.92
Build dir: /var/cache/scratchpkg/work/babl/src/babl-0.1.92/builddir
Build type: native build
Project name: babl
Project version: 0.1.92
Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc sanitycheckc.c -o sanitycheckc.exe -march=x86-64 -pipe -Os -fomit-frame-pointer -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /var/cache/scratchpkg/work/babl/src/babl-0.1.92/builddir/meson-private/sanitycheckc.exe
C compiler for the host machine: cc (gcc 11.2.0 "cc (Venom Linux 11.2.0-1) 11.2.0")
C linker for the host machine: cc ld.bfd 2.37
Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc sanitycheckc.c -o sanitycheckc.exe -march=x86-64 -pipe -Os -fomit-frame-pointer -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /var/cache/scratchpkg/work/babl/src/babl-0.1.92/builddir/meson-private/sanitycheckc.exe
C compiler for the build machine: cc (gcc 11.2.0 "cc (Venom Linux 11.2.0-1) 11.2.0")
C linker for the build machine: cc ld.bfd 2.37
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Program python3 found: YES (/usr/bin/python3)

../meson.build:58:5: ERROR: configuration_data.set10 got unknown keyword arguments "Description"
