### ISSUE TITLE
Port request (packages suckless)

### ISSUE THREAD

**Issue by lumarogit** [venomlinux/ports#581]
Hello, I would like to have these packages in the main repository to build my environment on Venom Linux, no rush:

-----
**pkgname=pipe-viewer**
version=0.2.0 or newer
homepage="https://github.com/trizen/pipe-viewer"
distfiles="https://github.com/trizen/pipe-viewer/archive/${version}.tar.gz"

**pkgname=numlockx** 
version=1.2 or newer
homepage="http://www.mike-devlin.com/linux/README-numlockx.htm"
distfiles="${DEBIAN_SITE}/main/n/${pkgname}/${pkgname}_${version}.orig.tar.gz"

**pkgname=herbe**
version=1.0.0 or newer
homepage="https://github.com/dudik/herbe"
distfiles="${homepage}/archive/${version}.tar.gz"

**pkgname=dwm**
version=6.3
homepage="http://dwm.suckless.org"
distfiles="https://dl.suckless.org/dwm/dwm-${version}.tar.gz"

**pkgname=st**
version=0.8.5 or newer
homepage="https://st.suckless.org"
distfiles="https://dl.suckless.org/${pkgname}/${pkgname}-${version}.tar.gz"

**pkgname=slock**
version=1.4 or newer
homepage="http://tools.suckless.org/slock"
distfiles="http://dl.suckless.org/tools/slock-${version}.tar.gz"

**pkgname=slstatus**
version=20180708 or newer
homepage="https://tools.suckless.org/slstatus/"
distfiles="https://github.com/drkhsh/slstatus/archive/${_commit}.tar.gz"

**pkgname=trash-cli**
version=0.20.12.26 or newer
homepage="https://github.com/andreafrancia/trash-cli"
distfiles="https://github.com/andreafrancia/trash-cli/archive/${version}.tar.gz"

-------
Thanks !!!

**Comment by Spacefreak18** [comment]
we do already have dwm in the ports tree

which brings up a good question, i use many of the suckless tools myself, and they have a paradigm where each person has custom patches that need to be applied to the code.

Is everyone essentially going to have their own fork of the ports tree?

the only other option i can think of is to have a directory that scratch looks in for patches.

I'd be interested to here what the other devs around here have to say, i'm leaning toward option 1 i think.

**Comment by Spacefreak18** [comment]
and i didn't mean to hijack your issue,

but i imagine you have special patches you'd wish to apply to dwm. I'd recommend you fork the repo, and attempt to modify the port for dwm to apply your patches, as a start. And you may find it's not that difficult and you'll be able to write ports for the other packages as well. 

I think they're useful tools, some I didn't know about that I'd like to try myself! :)

**Comment by lumarogit** [comment]
Mi localport:

https://git.disroot.org/lumaro/dotfiles/src/branch/master/venom/usr/ports/localport

**Comment by Spacefreak18** [comment]
nice!! you should make a pull request! Is it possble across different git platforms?

**Comment by Deecellar** [comment]
I think the basis without any configuration should exist (or minimal configuration if something doesn't work with venom i guess) but is needed to be manually overriden for the user (you can shadow packages having it first, or naming it different and alias a package to another as described in [Venom Linux Wiki about the package manager](https://venomlinux.org/wiki#package-manager.introduction)

**Comment by Spacefreak18** [comment]
> I think the basis without any configuration should exist (or minimal configuration if something doesn't work with venom i guess) but is needed to be manually overriden for the user (you can shadow packages having it first, or naming it different and alias a package to another as described in [Venom Linux Wiki about the package manager](https://venomlinux.org/wiki#package-manager.introduction)

I agree the basis has to exist, and what you describe is the way to do it now. It just feels like a bit of an antipattern. I'm just pointing out that gentoo has a way to basically add patches to any build. On a distro like this, a lot of people are going to use a lot of suckless tools, and everyone has custom patches for those.

**Comment by lumarogit** [comment]
Alright.
