### ISSUE TITLE
main/alsa-utils-1.2.9-4 building fails with glibc-2.36

### ISSUE THREAD

**Issue by Ouaille-Aime-Scier** [venomlinux/ports#5982]
Hello Venom's team,

After @lumarogit commit "alsa-utils: fix build with Glibc-2.38" , alsa-utils-1.2.9-4 compilation fails due to the fact that this fix is for glibc-2.38 which is not the venom4/core repo version (2.36 version).

Thanks in advance.

**Comment by lumarogit** [comment]
Hi, copy alsa-utils port in a local repo and edit it, comment the line thats apply the fix and install it. Check the wiki for create a local repo.

**Comment by Ouaille-Aime-Scier** [comment]
> Hi, copy alsa-utils port in a local repo and edit it, comment the line thats apply the fix and install it. Check the wiki for create a local repo.

Hi Luis, ok so I will do as proposed, I already have a local repo for libreoffice-lang-pack, thanks.
