### ISSUE TITLE
main/mate-panel-1.27.0 build fails due to msgfmt

### ISSUE THREAD

**Issue by Ouaille-Aime-Scier** [venomlinux/ports#5988]
See build.log attached.

Seems to be this type of bug : [https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=3f92e0d248944ecb3e4ba11f20e03334ec0c4610](url)

[build.log](https://github.com/venomlinux/ports/files/12347019/build.log)

**Comment by lumarogit** [comment]
Hi, mate* downgraded to 1.26.x, please, check again and feed back. Open new issue if build fails again with downgraded version. Thanks !

**Comment by Ouaille-Aime-Scier** [comment]
> Hi, mate* downgraded to 1.26.x, please, check again and feed back. Open new issue if build fails again with downgraded version. Thanks !

Hi Luis, I will reinstall Mate desktop this week-end when coming home. Thanks for all.

**Comment by Ouaille-Aime-Scier** [comment]
Hi Luis,

Mate is reinstalled on my laptop but eom and pluma don't build because of libpeas version if I understand correctly : 
`configure: error: Package requirements (
	libxml-2.0 >= 2.5.0
	glib-2.0 >= 2.50.0
	gmodule-2.0
	gthread-2.0 >= 2.13.0
	gio-2.0 >= 2.50.0
	gtk+-3.0 >= 3.22.0
	gtksourceview-4 >= 4.0.2
	libpeas-1.0 >= 1.2.0
	libpeas-gtk-1.0 >= 1.2.0
) were not met:

Package 'libpeas-1.0', required by 'virtual:world', not found
Package 'libpeas-gtk-1.0', required by 'virtual:world', not found`
