### ISSUE TITLE
Compressed Linux Firmware

### ISSUE THREAD

**Issue by itsManjeet** [venomlinux/ports#6359]
Issue: 
Currently the package `linux-firmware` generate uncompressed binary blob that take a lot of disk space, After the release of Linux 5.19 we have a option for zstd compressed binary blob of linux firmware with negligible decompression overhead.

Targeted Ports:
`main/linux` - Need to enable the FW_LOADER_COMPRESS{,_ZSTD,_XZ} configurations to support .zst or .xz compressed firmware.
`main/linux-firmware` - make install-zst or install-xz for compressed firmware installation

**Comment by lumarogit** [comment]
Oh nice, i'll study it. Thanks.

**Comment by ghost** [comment]
I'll suggest xz, zstd is a thing developed by Facebook 😁

**Comment by lumarogit** [comment]
Yeah, XZ is my choice xDD

**Comment by lumarogit** [comment]
It is already implemented in Venom and works fine.
