### ISSUE TITLE
Linux-lts fails compilation

### ISSUE THREAD

**Issue by Pelle-B** [venomlinux/ports#654]
The last lines are:

`
 CC [M]  mm/z3fold.o
  AR      mm/built-in.a
==> ERROR: Build failed: linux-lts-5.15.44-1`

**Comment by Pelle-B** [comment]
An error message before that is
`make[1]: *** [kernel/Makefile:160: kernel/kheaders_data.tar.xz] Error 127
make: *** [Makefile:1868: kernel] Error 2
make: *** Waiting for unfinished jobs....`

**Comment by emmett1** [comment]
Still not helping.

**Comment by Pelle-B** [comment]
That are the only error messages I get. I tried redownloading and I ran revdep -r.
