### ISSUE TITLE
error: git-remote-https died of signal 4

### ISSUE THREAD

**Issue by zebulon2020** [venomlinux/ports#7394]
I have installed the latest venom linux in QEMU/KVM, but when I ran the command `sudo portsync` or `sudo scratch sync`  , it showed that "error: git-remote-https died of signal 4" . 

The version of git is 2.42.1.

I tried some solutions ,such as `export GNUTLS_CPUID_OVERRIDE=0x1` , but it did't work.

**Comment by Visone-Selektah** [comment]
It's an error of curl. Download the sources you need and put them in `/var/cache/scratchpkg/sources` , then run `scratch install -fr curl`
to download the sources you can do this
` curl -LO "https://curl.haxx.se/download/curl-<version>.tar.xz`
